"""图床服务 - 接口文档与在线调试数据

数据与 API/apis/ImageHosting/ 实际实现对齐（服务策略 /api/ImageHosting/ 默认需签名）：
- scdn： scdn.io 图床（上传图片，返回 CDN 直链）
- picui：PicUI 图床（上传图片 + 服务端 Token 池管理）
"""
from .schema import ChannelSpec, EndpointSpec, ParamSpec, ResponseFieldSpec, ServiceSpec

SERVICE = ServiceSpec(
    slug='image_hosting',
    name='图床服务',
    prefix='/api/ImageHosting/',
    summary='图片外链托管：上传图片（或 ≤10 秒短视频）返回可直链访问的 CDN 地址，支持输出格式、加密与存储位置选择。当前接入 2 条线路。',
    keywords='图床API,免费图床,图片外链,图片CDN',
    intro=[
        '图床服务把图片上传到第三方托管平台并返回可直接引用的 CDN 外链，适合做站点配图、Markdown 图床、'
        '用户头像托管等场景，省去自建存储与带宽。',
        'scdn 线路支持上传本地图片或传入远程图片 URL，服务端按内容 SHA-256 秒传——同一张图片重复上传'
        '会直接返回已有链接，不会额外占用容量；picui 线路附带服务端 Token 池管理，'
        '可查看各 Token 的已用与剩余容量，并支持批量补充 Token。',
        '两条线路均需项目签名。第三方图床的链接可用性由对方平台决定，重要图片建议自行留存原图。',
    ],
    channels=[
        ChannelSpec(
            slug='scdn',
            name='scdn.io 图床',
            provider='scdn.io（img.scdn.io）图片托管',
            auth_note='auth',
            note='上传图片返回外链；服务端按 SHA-256 秒传，重复图片直接返回已有链接。需项目签名调用。',
            endpoints=[
                EndpointSpec('upload', '上传图片', 'POST', '/api/ImageHosting/scdn/upload',
                             summary='上传一张图片，返回可直接引用的 CDN 外链。',
                             params=[
                                 ParamSpec('image', '图片文件', kind='file', required=False, accept='image/*',
                                           desc='本地图片文件（multipart 字段 image，支持 jpg/png/webp/gif/bmp/tiff）；与 image_url 二选一'),
                                 ParamSpec('image_url', '远程图片 URL', kind='text', required=False,
                                           placeholder='https://example.com/a.jpg',
                                           desc='远程图片地址（http/https），服务端代理拉取；与 image 二选一'),
                                 ParamSpec('output_format', '输出格式', kind='select', default='auto',
                                           options=[{'value': 'auto', 'label': 'auto（默认，静态图转 webp）'},
                                                    {'value': 'jpg', 'label': 'jpg'},
                                                    {'value': 'png', 'label': 'png'},
                                                    {'value': 'webp', 'label': 'webp'},
                                                    {'value': 'gif', 'label': 'gif'},
                                                    {'value': 'webp_animated', 'label': 'webp_animated（动图）'}],
                                           desc='选填：输出格式，默认 auto'),
                                 ParamSpec('cdn_domain', 'CDN 域名', kind='text',
                                           placeholder='留空由服务端自动选择',
                                           desc='选填：指定外链 CDN 域名（如 img.scdn.io），留空自动选择'),
                                 ParamSpec('storage_destination', '存储位置', kind='select',
                                           options=[{'value': '', 'label': '不传（默认 local）'},
                                                    {'value': 'local', 'label': 'local'},
                                                    {'value': 'telegram', 'label': 'telegram'},
                                                    {'value': 'r2', 'label': 'r2（Cloudflare R2）'}],
                                           desc='选填：存储位置'),
                                 ParamSpec('password_enabled', '启用密码', kind='select', default='false',
                                           options=[{'value': 'false', 'label': 'false（默认）'},
                                                    {'value': 'true', 'label': 'true（加密上传）'}],
                                           desc='选填：加密上传（加密图永不参与秒传）'),
                                 ParamSpec('image_password', '访问密码', kind='text',
                                           desc='选填：password_enabled=true 时必填'),
                                 ParamSpec('password_type', '密码模式', kind='select', default='plain',
                                           options=[{'value': 'plain', 'label': 'plain（普通密码）'},
                                                    {'value': 'qa', 'label': 'qa（问答式）'}],
                                           desc='选填：密码模式，默认 plain'),
                                 ParamSpec('password_question', '问题文本', kind='text',
                                           desc='选填：password_type=qa 时必填'),
                             ],
                             notes=['请求体为 multipart/form-data（文件字段 image，可直接用下方“选择文件”上传）；'
                                    '用 image_url 时也可用 application/x-www-form-urlencoded。',
                                    '服务端按 SHA-256 秒传：命中时 message 为「图片已存在，秒传成功！」，deduped=true。',
                                    '本服务需项目签名（app_id/timestamp/nonce/sign）；在线调试由服务端自动代签。'],
                             response_fields=[
                                 ResponseFieldSpec('url', 'string', 'CDN 外链地址'),
                                 ResponseFieldSpec('filename', 'string', '文件名'),
                                 ResponseFieldSpec('storage_backend', 'string', '存储后端'),
                                 ResponseFieldSpec('original_size', 'int', '原始大小（字节）'),
                                 ResponseFieldSpec('compressed_size', 'int', '压缩后大小（字节）'),
                                 ResponseFieldSpec('compression_ratio', 'float', '压缩率'),
                                 ResponseFieldSpec('deduped', 'bool', '是否命中秒传'),
                                 ResponseFieldSpec('password_protected', 'bool', '是否加密保护'),
                             ],
                             response_example='{"url": "https://img.scdn.io/xxxx.jpg", "filename": "xxxx.jpg", "storage_backend": "local", "original_size": 123456, "compressed_size": 98765, "compression_ratio": 80.01, "deduped": false, "password_protected": false}'),
            ],
        ),
        ChannelSpec(
            slug='picui',
            name='PicUI 图床',
            provider='PicUI（v2.picui.cn）图片托管',
            auth_note='auth',
            note='上传图片返回外链；PicUI 账号 Token 由服务端 Token 池统一持有并记账，容量用尽自动切换，调用方无需提供账号。需项目签名调用。',
            endpoints=[
                EndpointSpec('upload', '上传图片', 'POST', '/api/ImageHosting/picui/upload',
                             summary='上传一张图片，返回可直接引用的外链地址（含 html / markdown 等多种引用格式）。',
                             params=[
                                 ParamSpec('image', '图片文件', kind='file', required=True, accept='image/*',
                                           desc='本地图片文件（multipart 字段 image），必需'),
                                 ParamSpec('permission', '图片权限', kind='select',
                                           options=[{'value': '', 'label': '不传（PicUI 默认公开）'},
                                                    {'value': '1', 'label': '1（公开）'},
                                                    {'value': '0', 'label': '0（私有）'}],
                                           desc='选填：图片权限，留空使用 PicUI 默认值'),
                                 ParamSpec('strategy_id', '储存策略ID', kind='text', default='1',
                                           placeholder='默认 1',
                                           desc='选填：PicUI 储存策略 ID，默认 1（「普通用户」策略）'),
                                 ParamSpec('album_id', '相册ID', kind='text',
                                           desc='选填：目标相册 ID'),
                                 ParamSpec('expired_at', '过期时间', kind='text',
                                           placeholder='2026-12-31 23:59:59',
                                           desc='选填：图片过期时间，格式 yyyy-MM-dd HH:mm:ss'),
                                 ParamSpec('upload_token', '临时上传Token', kind='text',
                                           desc='选填：PicUI 临时上传 Token（对应其 token 字段），一般不传'),
                             ],
                             notes=['请求体为 multipart/form-data（文件字段 image，可直接用下方“选择文件”上传）。',
                                    'PicUI 账号 Token 由服务端 Token 池自动选取，调用方无需（也无法）指定；'
                                    '上传成功后按 PicUI 返回的图片大小扣减该 Token 容量，容量用尽自动删除并切换下一个。',
                                    '令牌池告警：上传后若池内剩余容量跌破 50MB，系统会自动向管理员邮箱'
                                    '（环境变量 QQ_MAIL_ACCOUNT，未配置则不发送）发送一封补货提醒邮件；'
                                    '该告警只在「跌破」的那一次发送，补货回到 50MB 以上后再次跌破才会重新告警。',
                                    'Token 池为空或容量均已用尽时返回 50002，请先调用「导入 Token」接口补充。',
                                    '本服务需项目签名（app_id/timestamp/nonce/sign）；在线调试由服务端自动代签。'],
                             response_fields=[
                                 ResponseFieldSpec('url', 'string', '图片外链地址'),
                                 ResponseFieldSpec('name', 'string', '文件名'),
                                 ResponseFieldSpec('pathname', 'string', '存储路径'),
                                 ResponseFieldSpec('origin_name', 'string', '原始文件名'),
                                 ResponseFieldSpec('size_kb', 'int', '文件大小（KB）'),
                                 ResponseFieldSpec('size_bytes', 'int', '文件大小（字节）'),
                                 ResponseFieldSpec('mimetype', 'string', 'MIME 类型'),
                                 ResponseFieldSpec('extension', 'string', '扩展名'),
                                 ResponseFieldSpec('md5', 'string', 'MD5 值'),
                                 ResponseFieldSpec('sha1', 'string', 'SHA-1 值'),
                                 ResponseFieldSpec('links', 'object', '多种引用格式'),
                                 ResponseFieldSpec('links.html', 'string', 'HTML 引用'),
                                 ResponseFieldSpec('links.bbcode', 'string', '论坛 BBCode 引用'),
                                 ResponseFieldSpec('links.markdown', 'string', 'Markdown 图片'),
                                 ResponseFieldSpec('links.markdown_with_link', 'string', '带链接的 Markdown'),
                                 ResponseFieldSpec('links.thumbnail_url', 'string', '缩略图地址'),
                             ],
                             response_example='{"url": "https://v2.picui.cn/i/2026/07/01/xxxx.jpg", "name": "xxxx.jpg", "pathname": "/i/2026/07/01/xxxx.jpg", "origin_name": "photo.jpg", "size_kb": 120, "size_bytes": 122880, "mimetype": "image/jpeg", "extension": "jpg", "md5": "0f3d2c1b4a5968778695a4b3c2d1e0f1", "sha1": "0f3d2c1b4a5968778695a4b3c2d1e0f1a2b3c4d", "links": {"html": "<img src=\\"https://v2.picui.cn/i/2026/07/01/xxxx.jpg\\">", "bbcode": "[img]https://v2.picui.cn/i/2026/07/01/xxxx.jpg[/img]", "markdown": "![xxxx.jpg](https://v2.picui.cn/i/2026/07/01/xxxx.jpg)", "markdown_with_link": "[![xxxx.jpg](https://v2.picui.cn/i/2026/07/01/xxxx.jpg)](https://v2.picui.cn/i/2026/07/01/xxxx.jpg)", "thumbnail_url": "https://v2.picui.cn/i/2026/07/01/xxxx.jpg"}}'),
                EndpointSpec('list_tokens', '查询 Token 池', 'GET', '/api/ImageHosting/picui/tokens',
                             summary='查看 Token 池整体容量与每个 Token 的已用 / 剩余容量（Token 已脱敏）。',
                             params=[],
                             notes=['容量同时提供 MB（保留 2 位小数，便于阅读）与字节（便于计算）两种单位。',
                                    '容量用尽（已用 ≥ 容量）的 Token 会被自动删除，因此 items 中出现的 Token 均可继续使用；'
                                    '服务器只做容量记账，不参与图片存储。'],
                             response_fields=[
                                 ResponseFieldSpec('count', 'int', '池内可用 Token 数量'),
                                 ResponseFieldSpec('total_capacity_mb', 'float', '总容量合计（MB）'),
                                 ResponseFieldSpec('total_capacity_bytes', 'int', '总容量合计（字节）'),
                                 ResponseFieldSpec('total_used_mb', 'float', '已用容量合计（MB）'),
                                 ResponseFieldSpec('total_used_bytes', 'int', '已用容量合计（字节）'),
                                 ResponseFieldSpec('total_remaining_mb', 'float', '剩余容量合计（MB，看它判断补货）'),
                                 ResponseFieldSpec('total_remaining_bytes', 'int', '剩余容量合计（字节）'),
                                 ResponseFieldSpec('items', 'array', '每个 Token 的容量明细'),
                                 ResponseFieldSpec('items[].token', 'string', 'Token 脱敏值（留首 6 末 4）'),
                                 ResponseFieldSpec('items[].capacity_mb', 'float', '该 Token 总容量（MB）'),
                                 ResponseFieldSpec('items[].capacity_bytes', 'int', '该 Token 总容量（字节）'),
                                 ResponseFieldSpec('items[].used_mb', 'float', '该 Token 已用（MB）'),
                                 ResponseFieldSpec('items[].used_bytes', 'int', '该 Token 已用（字节）'),
                                 ResponseFieldSpec('items[].remaining_mb', 'float', '该 Token 剩余（MB）'),
                                 ResponseFieldSpec('items[].remaining_bytes', 'int', '该 Token 剩余（字节）'),
                                 ResponseFieldSpec('items[].create_time', 'string', '该 Token 的入库时间'),
                             ],
                             response_example='{"count": 1, "total_capacity_mb": 50.0, "total_capacity_bytes": 52428800, "total_used_mb": 12.34, "total_used_bytes": 12942336, "total_remaining_mb": 37.66, "total_remaining_bytes": 39486464, "items": [{"token": "657|uN****afdb", "capacity_mb": 50.0, "capacity_bytes": 52428800, "used_mb": 12.34, "used_bytes": 12942336, "remaining_mb": 37.66, "remaining_bytes": 39486464, "create_time": "2026-09-01 10:00:00"}]}'),
                EndpointSpec('add_tokens', '导入 Token', 'POST', '/api/ImageHosting/picui/tokens',
                             summary='向 Token 池新增一个或多个 Token（支持直接输入，也支持上传按行存放的 Token 文件）。',
                             params=[
                                 ParamSpec('tokens', 'Token', kind='textarea', repeatable=True,
                                           repeat_hint='可重复传参，或用逗号、换行分隔一次提交多个',
                                           placeholder='657|xxxxxxxxxxxxxxxx',
                                           desc='选填：待新增的 Token，可多个（与 token_file 至少传一项）'),
                                 ParamSpec('token_file', 'Token 文件', kind='file', accept='.txt,text/plain',
                                           desc='选填：文本文件，按行存放 Token（一行一个，UTF-8）'),
                                 ParamSpec('capacity_mb', '单个容量(MB)', kind='number', default='50',
                                           desc='选填：每个 Token 的容量（MB），默认 50'),
                             ],
                             notes=['Token 唯一：同一个 Token 只会入库一条，重复导入不会重复写入'
                                    '（库中已存在、或同一批请求里重复出现的，都计入 duplicated 跳过）。',
                                    'tokens 支持重复字段、逗号或换行分隔，一次可提交多个 Token；'
                                    'Token 内不能含空格等空白字符（文件里若带注释/多余列会被拒绝，避免导入无效 Token）。',
                                    'token_file 为按行存放 Token 的文本文件（一行一个），可与 tokens 同时使用。',
                                    '单次最多导入 1000 个 Token；本服务需项目签名（app_id/timestamp/nonce/sign）。'],
                             response_fields=[
                                 ResponseFieldSpec('submitted', 'int', '本次提交的 Token 数（去重后）'),
                                 ResponseFieldSpec('created', 'int', '实际新增数量'),
                                 ResponseFieldSpec('duplicated', 'int', '因已存在而跳过的数量'),
                                 ResponseFieldSpec('duplicated_tokens', 'array', '被跳过的 Token 脱敏列表'),
                                 ResponseFieldSpec('capacity_bytes', 'int', '每个新 Token 的容量（字节）'),
                                 ResponseFieldSpec('capacity_mb', 'float', '每个新 Token 的容量（MB）'),
                             ],
                             response_example='{"submitted": 3, "created": 2, "duplicated": 1, "duplicated_tokens": ["657|uN****afdb"], "capacity_bytes": 52428800, "capacity_mb": 50.0}'),
            ],
        ),
    ],
)
