"""音乐服务 - 接口文档与在线调试数据

数据与 API/apis/musics/ 实际实现对齐，两条线路（分类树中 /api/music/ 为需签名）：
- 爱听音乐网 2t58：4 个只读接口（爬虫抓取，均为 GET）
- 小影音乐 xiaoying：Music / MusicSource 的 RESTful 增删改查 + 批量 JSON 导入
"""
from .schema import ChannelSpec, EndpointSpec, ParamSpec, ServiceSpec

# 通用歌手多值提示（小影音乐支持同一字段多次传，页面调试用逗号/换行拆分后多次发送）
_SINGER_HINT = '多个歌手用逗号或换行分隔（服务端会按多次传参拆成歌手列表）'

SERVICE = ServiceSpec(
    slug='music',
    name='音乐服务',
    prefix='/api/music/',
    summary='音乐聚合能力：爱听音乐网抓取（首页/歌手/歌曲/搜索）与小影音乐自有曲库的增删改查。当前接入 2 条线路。',
    channels=[
        ChannelSpec(
            slug='2t58',
            name='爱听音乐网 2t58',
            provider='2t58.com 网页抓取（只读）',
            auth_note='auth',
            note='抓取热门/歌手/歌曲/搜索数据。url 参数必须为 2t58.com 域名地址。',
            endpoints=[
                EndpointSpec('home', '首页数据', 'GET', '/api/music/2t58/home',
                             summary='返回热门歌手、歌曲飙升榜、流行趋势榜三个模块。'),
                EndpointSpec('singer', '歌手详情', 'GET', '/api/music/2t58/singer',
                             summary='歌手基本信息 + 歌曲列表（含分页）。',
                             params=[ParamSpec('url', '歌手页 URL', kind='text', required=True,
                                               placeholder='https://www.2t58.com/singer/bm1z/1.html',
                                               desc='2t58.com 歌手歌曲列表页完整地址（必填）')]),
                EndpointSpec('song', '歌曲详情', 'GET', '/api/music/2t58/song',
                             summary='歌曲基本信息 + 播放链接 + 歌词 + 每日推荐。',
                             params=[ParamSpec('url', '歌曲页 URL', kind='text', required=True,
                                               placeholder='https://www.2t58.com/song/d3dkc2t3.html',
                                               desc='2t58.com 歌曲详情页完整地址（必填）')]),
                EndpointSpec('search', '搜索音乐', 'GET', '/api/music/2t58/search',
                             summary='按关键词搜索歌曲（分页）。',
                             params=[
                                 ParamSpec('keyword', '关键词', kind='text', required=True,
                                           placeholder='如：王小草', desc='搜索关键词（必填）'),
                                 ParamSpec('page', '页码', kind='number', default='1',
                                           desc='选填：页码，正整数，默认 1'),
                             ]),
            ],
        ),
        ChannelSpec(
            slug='xiaoying',
            name='小影音乐',
            provider='自有曲库（Music/MusicSource 数据）',
            auth_note='auth',
            note='音乐与其播放源的 RESTful 增删改查；音乐详情接口会同时返回其全部播放源。',
            endpoints=[
                EndpointSpec('list_musics', '音乐列表查询', 'GET', '/api/music/xiaoying/musics',
                             summary='按关键词/在线状态查询音乐（分页）；不传 online 时默认只返回在线音乐。',
                             params=[
                                 ParamSpec('keyword', '关键词', kind='text',
                                           placeholder='名称或歌手', desc='选填：匹配音乐名称/歌手'),
                                 ParamSpec('online', '在线状态', kind='select',
                                           options=[{'value': '', 'label': '不传（默认仅在线）'},
                                                    {'value': 'true', 'label': 'true（仅在线）'},
                                                    {'value': 'false', 'label': 'false（含离线）'}],
                                           desc='选填：true/false'),
                                 ParamSpec('page', '页码', kind='number', default='1', desc='选填：默认 1'),
                                 ParamSpec('page_size', '每页条数', kind='number', default='10',
                                           desc='选填：1-100，默认 10'),
                             ]),
                EndpointSpec('create_music', '创建音乐', 'POST', '/api/music/xiaoying/musics',
                             summary='新建一条音乐，返回 music_id（UUID），供详情/播放源关联使用。',
                             params=[
                                 ParamSpec('name', '音乐名称', kind='text', required=True,
                                           placeholder='如：晴天', desc='音乐名称（必填）'),
                                 ParamSpec('singer', '歌手', kind='textarea', required=True,
                                           repeatable=True, repeat_hint=_SINGER_HINT,
                                           placeholder='周杰伦\n蔡依林', desc='歌手（必填，至少一位）'),
                                 ParamSpec('online', '在线状态', kind='select',
                                           options=[{'value': 'true', 'label': 'true（在线，默认）'},
                                                    {'value': 'false', 'label': 'false（离线）'}],
                                           default='true', desc='选填：默认 true'),
                             ]),
                EndpointSpec('music_detail', '获取音乐详情', 'GET',
                             '/api/music/xiaoying/musics/<uuid>',
                             summary='按音乐 UUID 查询单条音乐，同时返回其全部播放源（music_sources）。',
                             params=[ParamSpec('music_id', '音乐 UUID', kind='text', required=True,
                                               placeholder='创建音乐返回的 music_id',
                                               desc='路径参数：音乐 UUID（文档页代调时请替换 URL 中的 <uuid>）')]),
                EndpointSpec('update_music', '更新音乐', 'PATCH',
                             '/api/music/xiaoying/musics/<uuid>',
                             summary='部分字段更新音乐（singer 为整体替换）。',
                             params=[
                                 ParamSpec('music_id', '音乐 UUID', kind='text', required=True,
                                           desc='路径参数：要更新的音乐 UUID'),
                                 ParamSpec('name', '音乐名称', kind='text', desc='选填：新名称'),
                                 ParamSpec('singer', '歌手', kind='textarea', repeatable=True,
                                           repeat_hint=_SINGER_HINT, desc='选填：整体替换歌手列表'),
                                 ParamSpec('online', '在线状态', kind='select',
                                           options=[{'value': 'true', 'label': 'true'},
                                                    {'value': 'false', 'label': 'false'}],
                                           desc='选填：true/false'),
                             ]),
                EndpointSpec('delete_music', '删除音乐', 'DELETE',
                             '/api/music/xiaoying/musics/<uuid>',
                             summary='按 UUID 删除音乐（其播放源级联删除）。',
                             params=[ParamSpec('music_id', '音乐 UUID', kind='text', required=True,
                                               desc='路径参数：要删除的音乐 UUID')]),
                EndpointSpec('create_source', '创建播放源', 'POST', '/api/music/xiaoying/music_sources',
                             summary='给某首音乐新增一个播放链接。',
                             params=[
                                 ParamSpec('music_id', '音乐 UUID', kind='text', required=True,
                                           placeholder='创建音乐返回的 UUID',
                                           desc='音乐 UUID（必填，须已存在）'),
                                 ParamSpec('url', '播放链接', kind='text', required=True,
                                           placeholder='https://...', desc='播放地址（必填，需合法 URL）'),
                             ]),
                EndpointSpec('update_source', '更新播放源', 'PATCH',
                             '/api/music/xiaoying/music_sources/<uuid>',
                             summary='部分字段更新播放源（music_id/url）。',
                             params=[
                                 ParamSpec('source_id', '播放源 UUID', kind='text', required=True,
                                           desc='路径参数：播放源 UUID'),
                                 ParamSpec('url', '播放链接', kind='text', desc='选填：新播放地址'),
                             ]),
                EndpointSpec('delete_source', '删除播放源', 'DELETE',
                             '/api/music/xiaoying/music_sources/<uuid>',
                             summary='按 UUID 删除播放源。',
                             params=[ParamSpec('source_id', '播放源 UUID', kind='text', required=True,
                                               desc='路径参数：播放源 UUID')]),
                EndpointSpec('import_musics', '批量导入', 'POST', '/api/music/xiaoying/import',
                             summary='上传 JSON 文件批量导入音乐+播放源（单文件 ≤10MB、单次 ≤9999 条，不去重）。',
                             params=[
                                 ParamSpec('file', 'JSON 文件', kind='textarea', required=True,
                                           placeholder='[{"name":"晴天","singer":["周杰伦"],"online":true,"music_sources":["https://..."]}]',
                                           desc='multipart 文件字段 file，内容为 JSON 数组。'
                                                '页面在线调试暂不支持文件上传，请在代码中调用。'),
                             ],
                             notes=['示例单条：{"name":"晴天","singer":["周杰伦"],"online":true,"music_sources":["https://..."]}',
                                    '部分成功：单条记录失败会整体回滚该条，响应返回 failures 明细。']),
            ],
        ),
    ],
)
