# Generated by Django 6.0.5 on 2026-08-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='网站名称')),
                ('url', models.URLField(max_length=500, verbose_name='网站链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='网站描述')),
                ('logo', models.URLField(blank=True, default='', max_length=500, verbose_name='Logo链接')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='分类')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式')),
                ('sort', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'seo_friend_link',
                'ordering': ['-sort', '-create_time'],
            },
        ),
    ]
