# Generated by Django 6.0.5 on 2026-08-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_friend_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='name',
            field=models.CharField(max_length=100, verbose_name='网站名称'),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='网站链接'),
        ),
    ]
