# Generated by Django 6.0.6 on 2026-08-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_friend_link_url_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='音乐名称')),
                ('singer', models.CharField(max_length=200, verbose_name='音乐歌手')),
                ('online', models.BooleanField(db_index=True, default=True, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'music',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MusicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.URLField(max_length=500, verbose_name='播放链接')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_sources', to='API.music', verbose_name='关联音乐')),
            ],
            options={
                'verbose_name': '播放源',
                'verbose_name_plural': '播放源',
                'db_table': 'music_source',
                'ordering': ['-create_time'],
            },
        ),
    ]
