# Generated by Django 6.0.6 on 2026-08-25 06:59

import json

from django.db import migrations, models


def convert_singer_to_json_list(apps, schema_editor):
    """将旧的字符串歌手转为 JSON 数组字符串，确保 AlterField 后 json.loads 可解析

    注意：此时 singer 仍是 CharField，需用 json.dumps 写出合法 JSON，
    不能直接赋 Python 列表（会被 str() 转成非 JSON 的单引号形式）。
    """
    Music = apps.get_model('API', 'Music')
    for music in Music.objects.all():
        if isinstance(music.singer, str):
            music.singer = json.dumps([music.singer], ensure_ascii=False)
            music.save(update_fields=['singer'])


def convert_json_list_to_string(apps, schema_editor):
    """反向：把 JSON 数组还原为字符串（取第一个歌手）"""
    Music = apps.get_model('API', 'Music')
    for music in Music.objects.all():
        if isinstance(music.singer, list) and music.singer:
            music.singer = music.singer[0]
            music.save(update_fields=['singer'])


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_music_id_alter_musicsource_id'),
    ]

    operations = [
        # 先转换旧数据（AlterField 前 singer 仍是 CharField，可安全读写）
        migrations.RunPython(convert_singer_to_json_list, convert_json_list_to_string),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.JSONField(default=list, verbose_name='音乐歌手'),
        ),
    ]
