# Generated by Django 6.0.6 on 2026-08-25 07:07

# 说明：原引用 API.models.music（模型重构前路径）；Music 域迁移至 API.models.Music.music 后同步调整，
# 不改变迁移语义，仅保持新环境首次 migrate 时可正确加载 RawJSONEncoder。
from API.models.Music.music import RawJSONEncoder
from django.db import migrations, models


def reencode_singer_json(apps, schema_editor):
    """将存量 singer 用新编码器（ensure_ascii=False）重写入库

    旧数据由默认编码器写入，中文为 \\uXXXX 转义形式（如 "\\u5468\\u6770\\u4f26"），
    导致基于数据库文本的 LIKE 模糊搜索（singer__icontains）失效。
    这里重存一遍，使数据库内为原始中文，便于按歌手搜索。
    """
    Music = apps.get_model('API', 'Music')
    for music in Music.objects.all():
        music.singer = list(music.singer)
        music.save(update_fields=['singer'])


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_music_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.JSONField(default=list, encoder=RawJSONEncoder, verbose_name='音乐歌手'),
        ),
        migrations.RunPython(reencode_singer_json, migrations.RunPython.noop),
    ]
