# Generated by Django 6.0.6 on 2026-08-29 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_music_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(db_index=True, help_text='系统分配，纯数字 6-12 位，全局唯一，不可自定义', max_length=12, unique=True, verbose_name='账号')),
                ('username', models.CharField(blank=True, default='', help_text='用户自填，允许重复，仅作展示用途', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(help_text='Django PBKDF2 加盐哈希，不存明文', max_length=128, verbose_name='密码哈希')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='True=正常，False=封禁', verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='应用名称')),
                ('app_id', models.CharField(db_index=True, help_text='公开标识，调用用户中心接口时携带', max_length=32, unique=True, verbose_name='APPID')),
                ('app_secret', models.CharField(help_text='签名密钥，HMAC-SHA256 签名用，仅项目方与用户中心知道', max_length=64, verbose_name='APPSECRET')),
                ('token_expire_days', models.PositiveIntegerField(default=7, help_text='该项目的登录 Token 默认有效期（天），后台可修改', verbose_name='Token有效天数')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='True=正常，False=停止该项目接入权限', verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '接入项目',
                'verbose_name_plural': '接入项目',
                'db_table': 'user_app',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='TokenID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('expire_time', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('last_active_time', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('app', models.ForeignKey(help_text='Token 绑定项目，不同项目的 Token 互不通用', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='API.userapp', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='API.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户Token',
                'verbose_name_plural': '用户Token',
                'db_table': 'user_token',
                'ordering': ['-create_time'],
            },
        ),
    ]
