# Generated by Django 6.0.6 on 2026-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_user_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='app_id',
            field=models.CharField(blank=True, db_index=True, help_text='公开标识，系统自动生成（app_ 前缀），创建后固定', max_length=32, unique=True, verbose_name='APPID'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='app_secret',
            field=models.CharField(blank=True, help_text='签名密钥，系统自动生成（sk_ 前缀），HMAC-SHA256 签名用，创建后固定', max_length=64, verbose_name='APPSECRET'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='name',
            field=models.CharField(help_text='应用名称全局唯一，不可重复', max_length=100, unique=True, verbose_name='应用名称'),
        ),
    ]
