# Generated by Django 6.0.6 on 2026-08-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_user_center_auto_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuthPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='如：短信验证码服务、用户中心-登录接口', max_length=100, verbose_name='服务名称')),
                ('path_prefix', models.CharField(help_text='服务级如 /api/sms_verify/ ；接口级如 /api/user_center/users/login（完整路径），最长前缀匹配生效', max_length=200, unique=True, verbose_name='URL前缀')),
                ('level', models.CharField(choices=[('service', '服务级'), ('endpoint', '接口级')], default='service', help_text='服务级=整个服务统一开关；接口级=覆盖服务级默认值，仅对单接口生效', max_length=10, verbose_name='级别')),
                ('requires_auth', models.BooleanField(db_index=True, default=False, help_text='开启后，该服务/接口的调用方必须携带 APPID+APPSECRET 签名，否则拒绝访问', verbose_name='要求用户中心认证')),
                ('status', models.BooleanField(default=True, help_text='停用后该规则不参与匹配（恢复默认开放）', verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'API服务认证策略',
                'verbose_name_plural': 'API服务认证策略',
                'ordering': ('-level', '-create_time'),
            },
        ),
    ]
