# Generated by Django 6.0.6 on 2026-08-29 23:33

from django.db import migrations


def create_default_policies(apps, schema_editor):
    """按现状初始化 API 服务认证策略：
    - 用户中心 /api/user_center/：要求用户中心认证
    - 短信验证码 /api/sms_verify/：要求用户中心认证
    - 其余服务（图形认证等）默认开放，无需配置规则
    """
    ApiAuthPolicy = apps.get_model('API', 'ApiAuthPolicy')
    defaults = [
        ('用户中心服务', '/api/user_center/', 'service', True,
         '用户注册/登录/验证等接口，必须携带 APPID+APPSECRET 签名'),
        ('短信验证码服务', '/api/sms_verify/', 'service', True,
         '短信发送/核验接口，必须携带签名，防止短信被滥用'),
    ]
    for name, path_prefix, level, requires_auth, remark in defaults:
        ApiAuthPolicy.objects.get_or_create(
            path_prefix=path_prefix,
            defaults={
                'name': name,
                'level': level,
                'requires_auth': requires_auth,
                'remark': remark,
            },
        )


def remove_default_policies(apps, schema_editor):
    ApiAuthPolicy = apps.get_model('API', 'ApiAuthPolicy')
    ApiAuthPolicy.objects.filter(path_prefix__in=[
        '/api/user_center/',
        '/api/sms_verify/',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_apiauthpolicy'),
    ]

    operations = [
        migrations.RunPython(create_default_policies, remove_default_policies),
    ]
