# Generated by Django 6.0.6 on 2026-08-29 23:53
# 手工扩展：追加数据迁移 —— 自动扫描 API/apis/ 目录生成分类树，并迁移旧 ApiAuthPolicy 数据

import os
import re

import django.db.models.deletion
from django.db import migrations, models

# urls.py 中 path('x/', include('API.apis.xxx.urls')) 的解析规则
_INCLUDE_RE = re.compile(r"""path\(\s*['"]([^'"]*)['"]\s*,\s*include\(\s*['"](API\.apis\.[\w.]+)\.urls['"]\s*\)""")
_COMMENT_RE = re.compile(r'#\s*(.+)$')

# API/apis 目录绝对路径（迁移文件位于 API/migrations/ 下，向上两级到项目根再进 API/apis）
_API_APIS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'apis',
)


def _parse_include_lines(urls_path):
    """解析单个 urls.py，返回 [(url前缀, 模块路径, 注释名称)]"""
    result = []
    try:
        with open(urls_path, encoding='utf-8') as f:
            for line in f:
                m = _INCLUDE_RE.search(line)
                if not m:
                    continue
                prefix, module = m.group(1), m.group(2)
                cm = _COMMENT_RE.search(line)
                name = cm.group(1).strip() if cm else ''
                result.append((prefix, module, name))
    except OSError:
        pass
    return result


def build_category_tree(apps, schema_editor):
    """递归扫描 urls.py include 链，为每个服务目录建立分类节点（path_prefix 唯一）"""
    ApiCategory = apps.get_model('API', 'ApiCategory')

    def build(urls_path, parent, acc_prefix):
        for prefix, module, comment in _parse_include_lines(urls_path):
            if not prefix:
                # 空前缀（如 seo 的 path('', ...)）：不建独立节点，继续向下递归
                build(os.path.join(_API_APIS_DIR, module[len('API.apis.'):].replace('.', '/'), 'urls.py'),
                      parent, acc_prefix)
                continue
            child_prefix = acc_prefix + prefix
            name = comment or module.split('.')[-1]
            node, _ = ApiCategory.objects.get_or_create(
                path_prefix=child_prefix,
                defaults={'name': name, 'parent': parent},
            )
            build(os.path.join(_API_APIS_DIR, module[len('API.apis.'):].replace('.', '/'), 'urls.py'),
                  node, child_prefix)

    build(os.path.join(_API_APIS_DIR, 'urls.py'), None, '/api/')


def migrate_policies(apps, schema_editor):
    """把旧 ApiAuthPolicy 数据映射到分类树：
    requires_auth=True -> auth；requires_auth=False -> open。
    精确匹配优先，否则取能覆盖该策略范围的「最深」分类节点。
    """
    ApiCategory = apps.get_model('API', 'ApiCategory')
    ApiAuthPolicy = apps.get_model('API', 'ApiAuthPolicy')
    categories = list(ApiCategory.objects.all())
    for policy in ApiAuthPolicy.objects.all():
        node = next((c for c in categories if c.path_prefix == policy.path_prefix), None)
        if node is None:
            node = max(
                (c for c in categories if policy.path_prefix.startswith(c.path_prefix)),
                key=lambda c: len(c.path_prefix), default=None,
            )
        if node is None:
            continue
        node.auth_mode = 'auth' if policy.requires_auth else 'open'
        node.save(update_fields=['auth_mode'])


def migrate_data(apps, schema_editor):
    build_category_tree(apps, schema_editor)
    migrate_policies(apps, schema_editor)


def remove_data(apps, schema_editor):
    """反向迁移：删除自动生成且未被手动修改的分类节点（保守策略：全部清空）"""
    ApiCategory = apps.get_model('API', 'ApiCategory')
    ApiCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_init_api_auth_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('path_prefix', models.CharField(help_text='如 /api/user_center/ 、 /api/user_center/users/，请求路径按最长前缀匹配', max_length=200, unique=True, verbose_name='URL前缀')),
                ('auth_mode', models.CharField(choices=[('inherit', '跟随上级'), ('auth', '需要认证'), ('open', '开放')], default='inherit', help_text='inherit=跟随上级；auth=需要用户中心认证；open=开放（无需认证）', max_length=10, verbose_name='认证模式')),
                ('status', models.BooleanField(default=True, help_text='停用后该分类不参与匹配（恢复默认开放）', verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='API.apicategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': 'API服务分类',
                'verbose_name_plural': 'API服务分类',
                'ordering': ('path_prefix',),
            },
        ),
        migrations.RunPython(migrate_data, remove_data),
    ]
