# Generated by Django 6.0.6 on 2026-08-31 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_delete_apiauthpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(help_text='用途标识，如 email_verify 邮箱验证', max_length=50, unique=True, verbose_name='模板类型')),
                ('subject', models.CharField(help_text='邮件主题，可含变量，如 {{username}}', max_length=200, verbose_name='邮件标题')),
                ('html_body', models.TextField(help_text='支持变量: {{username}} {{code}} {{link}} {{expire_minutes}}', verbose_name='HTML正文')),
                ('description', models.CharField(blank=True, default='', help_text='模板用途说明，便于后台识别', max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_template',
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='邮箱登录凭证，全局唯一；注册时可选择绑定，绑定后需验证邮件才能登录', max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='绑定的邮箱是否已通过验证邮件确认，未验证不可用邮箱登录', verbose_name='邮箱已验证'),
        ),
        migrations.CreateModel(
            name='UserEmailVerify',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='验证ID')),
                ('email', models.EmailField(help_text='发起验证时填写的邮箱，便于核对', max_length=254, verbose_name='验证邮箱')),
                ('code', models.CharField(help_text='6 位数字验证码，验证形式为 code/both 时使用', max_length=6, verbose_name='验证码')),
                ('token', models.CharField(db_index=True, help_text='一次性激活链接标识，验证形式为 link/both 时使用', max_length=64, unique=True, verbose_name='激活链接Token')),
                ('expire_time', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='激活成功后置 True，一次性有效', verbose_name='是否已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifies', to='API.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '邮箱验证记录',
                'verbose_name_plural': '邮箱验证记录',
                'db_table': 'user_email_verify',
                'ordering': ['-create_time'],
            },
        ),
    ]
