# Generated by Django 6.0.6 on 2026-08-31 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_auth_methods(apps, schema_editor):
    """种子数据：初始化 email / phone 两种验证方式（后台可再调整开关）"""
    AuthMethod = apps.get_model('API', 'AuthMethod')
    AuthMethod.objects.get_or_create(
        type='email',
        defaults={'name': '邮箱', 'enabled': True,
                  'description': '邮箱注册/登录：注册发验证邮件，登录需邮箱已验证'},
    )
    AuthMethod.objects.get_or_create(
        type='phone',
        defaults={'name': '手机号', 'enabled': True,
                  'description': '手机号注册/登录：注册发短信验证码，登录需手机号已验证'},
    )


def migrate_email_verify_records(apps, schema_editor):
    """数据迁移：user_email_verify 存量记录平移至统一表 user_verify_record（type=email）"""
    Old = apps.get_model('API', 'UserEmailVerify')
    New = apps.get_model('API', 'UserVerifyRecord')
    for old in Old.objects.all().iterator():
        New.objects.create(
            id=old.id,
            user_id=old.user_id,
            type='email',
            credential=old.email,
            code=old.code,
            token=old.token,
            expire_time=old.expire_time,
            is_used=old.is_used,
            create_time=old.create_time,
            updated_time=old.updated_time,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_emailtemplate_user_email_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(db_index=True, help_text='类型标识（email / phone / 后续扩展），与代码逻辑对应', max_length=20, unique=True, verbose_name='方式类型')),
                ('name', models.CharField(help_text='后台展示名称（如 邮箱 / 手机号）', max_length=50, verbose_name='显示名称')),
                ('enabled', models.BooleanField(default=True, help_text='启用后该方式的注册 / 登录 / 验证均可用，关闭即整体停用', verbose_name='启用')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '认证方式配置',
                'verbose_name_plural': '认证方式配置',
                'db_table': 'auth_method',
                'ordering': ['type'],
            },
        ),
        migrations.RunPython(seed_auth_methods, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='手机号登录凭证（中国大陆 11 位数字），全局唯一；注册时可选择绑定，绑定后需短信验证才能登录', max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='绑定的手机号是否已通过短信验证码确认，未验证不可用手机号登录', verbose_name='手机号已验证'),
        ),
        migrations.CreateModel(
            name='UserVerifyRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='验证ID')),
                ('type', models.CharField(db_index=True, help_text='验证方式类型（email / phone / 后续扩展），与 AuthMethod.type 对应', max_length=20, verbose_name='验证方式')),
                ('credential', models.CharField(db_index=True, help_text='发起验证时填写的邮箱地址或手机号，便于核对', max_length=254, verbose_name='验证凭证')),
                ('code', models.CharField(help_text='6 位数字验证码，验证形式为 code/both 时使用', max_length=8, verbose_name='验证码')),
                ('token', models.CharField(blank=True, db_index=True, help_text='一次性激活链接标识，验证形式为 link/both 时使用，手机号方式为空', max_length=64, null=True, unique=True, verbose_name='激活链接Token')),
                ('expire_time', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='激活成功后置 True，一次性有效', verbose_name='是否已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_records', to='API.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '验证记录',
                'verbose_name_plural': '验证记录',
                'db_table': 'user_verify_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RunPython(migrate_email_verify_records, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='UserEmailVerify',
        ),
        migrations.AddIndex(
            model_name='userverifyrecord',
            index=models.Index(fields=['type', 'credential'], name='idx_verify_type_credential'),
        ),
    ]
