# Generated by Django 6.0.6 on 2026-09-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_authmethod_user_phone_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverifyrecord',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='两步注册暂存，完成注册建号时使用（不存明文）', max_length=128, verbose_name='暂存密码哈希'),
        ),
        migrations.AddField(
            model_name='userverifyrecord',
            name='scene',
            field=models.CharField(db_index=True, default='verify', help_text='register=两步注册意向 / login=登录验证码，区分验证码用途', max_length=20, verbose_name='验证场景'),
        ),
        migrations.AddField(
            model_name='userverifyrecord',
            name='username',
            field=models.CharField(blank=True, default='', help_text='两步注册暂存，完成注册建号时使用', max_length=50, verbose_name='暂存用户名'),
        ),
        migrations.AlterField(
            model_name='userverifyrecord',
            name='is_used',
            field=models.BooleanField(default=False, help_text='校验成功后置 True，一次性有效', verbose_name='是否已使用'),
        ),
        migrations.AlterField(
            model_name='userverifyrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='可空：两步注册意向在完成注册建号前无用户，建号后回填', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify_records', to='API.user', verbose_name='关联用户'),
        ),
        migrations.AddIndex(
            model_name='userverifyrecord',
            index=models.Index(fields=['scene', 'type', 'credential'], name='idx_verify_scene_type_cred'),
        ),
    ]
