# Generated by Django 6.0.6 on 2026-09-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_user_verify_record_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverifyrecord',
            name='register_batch',
            field=models.CharField(blank=True, db_index=True, help_text='两步注册：同一次注册请求（如同时绑定邮箱+手机号）共享批次，完成注册时合并为同一账号', max_length=36, null=True, verbose_name='注册批次'),
        ),
    ]
