# Generated by Django 6.0.6 on 2026-09-01 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_user_verify_record_register_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='反馈ID')),
                ('title', models.CharField(help_text='问题标题，简短描述', max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='问题详情（纯文本）', verbose_name='内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='pending', help_text='待处理/处理中/已解决/已关闭', max_length=20, verbose_name='状态')),
                ('app', models.ForeignKey(help_text='租户维度：反馈数据按项目隔离，子项目之间互不可见', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='API.userapp', verbose_name='所属项目')),
                ('user', models.ForeignKey(help_text='反馈提交者（UAC 用户，提交时经 Token 校验真实性）', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='API.user', verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '问题反馈',
                'verbose_name_plural': '问题反馈',
                'db_table': 'feedback',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='追加ID')),
                ('author_role', models.CharField(choices=[('user', '子项目用户'), ('admin', '站长')], default='user', help_text='user=子项目用户 / admin=站长', max_length=10, verbose_name='身份类型')),
                ('content', models.TextField(help_text='追加内容（纯文本）', verbose_name='内容')),
                ('feedback', models.ForeignKey(help_text='追加归属于某条反馈，同反馈下所有追加按时间平铺', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='API.feedback', verbose_name='所属反馈')),
                ('user', models.ForeignKey(blank=True, help_text='子项目用户追加者；站长回复时为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to='API.user', verbose_name='追加用户')),
            ],
            options={
                'verbose_name': '反馈追加',
                'verbose_name_plural': '反馈追加',
                'db_table': 'feedback_reply',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['app', 'status'], name='idx_feedback_app_status'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['app', 'create_time'], name='idx_feedback_app_time'),
        ),
    ]
