# Generated by Django 6.0.6 on 2026-09-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_feedback_feedbackreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreply',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='为空=一级评论；非空=回复某条评论（支持任意深度嵌套，删除父评论级联删除子孙）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='API.feedbackreply', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='feedback',
            field=models.ForeignKey(help_text='追加归属于某条反馈', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='API.feedback', verbose_name='所属反馈'),
        ),
        migrations.AddIndex(
            model_name='feedbackreply',
            index=models.Index(fields=['parent'], name='idx_freply_parent'),
        ),
    ]
