# Generated by Django 6.0.6 on 2026-09-04 15:47

import API.models.Projects.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_feedbackreply_parent_alter_feedbackreply_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicategory',
            name='status',
            field=models.BooleanField(default=True, help_text='停用后该分类不参与匹配（按全局默认处理，A-01 起默认需要认证）', verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='app_secret',
            field=API.models.Projects.app.EncryptedSecretField(blank=True, help_text='签名密钥，系统自动生成（sk_ 前缀），HMAC-SHA256 签名用，创建后固定；落库 AES 加密存储（S-06）', max_length=200, verbose_name='APPSECRET'),
        ),
    ]
