# Generated by Django 6.0.6 on 2026-09-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_apicategory_status_alter_userapp_app_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url_prefix', models.CharField(help_text='对应官网服务清单的 url_prefix，如 /api/music/', max_length=64, primary_key=True, serialize=False, verbose_name='服务路由前缀')),
                ('status', models.CharField(choices=[('open', '开放'), ('testing', '测试中'), ('maintenance', '维护中'), ('building', '建设中'), ('offline', '已下线')], max_length=16, verbose_name='服务状态')),
            ],
            options={
                'verbose_name': '服务状态配置',
                'verbose_name_plural': '服务状态配置',
                'db_table': 'api_service_status',
            },
        ),
    ]
