# Generated by Django 6.0.6 on 2026-09-10 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='验证码ID')),
                ('answer', models.CharField(help_text='校验依据；短有效期 + 一次性消费', max_length=16, verbose_name='标准答案')),
                ('kind', models.CharField(choices=[('char', '字符图片'), ('arithmetic', '算术')], default='char', help_text='char=字符图片 / arithmetic=算术', max_length=12, verbose_name='类型')),
                ('expire_time', models.DateTimeField(db_index=True, help_text='超过该时间即作废，需重新获取', verbose_name='过期时间')),
                ('used', models.BooleanField(default=False, help_text='一次性：校验一次即置为已用，防同一张图被反复尝试', verbose_name='已使用')),
            ],
            options={
                'verbose_name': '图形验证码',
                'verbose_name_plural': '图形验证码',
                'db_table': 'captcha_challenge',
                'ordering': ['-create_time'],
            },
        ),
    ]
