# Generated by Django 6.0.6 on 2026-09-10 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_captcha_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallStat',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='统计ID')),
                ('stat_date', models.DateField(help_text='按本地时区（Asia/Shanghai）日期切分', verbose_name='统计日期')),
                ('service', models.CharField(help_text='路径第 1 段，如 /api/email/', max_length=100, verbose_name='服务前缀')),
                ('path', models.CharField(help_text='不含查询串的请求路径', max_length=255, verbose_name='端点路径')),
                ('app_id', models.CharField(default='-', help_text='接入项目 APPID；开放接口与未认证请求记为 -', max_length=32, verbose_name='接入项目')),
                ('status_code', models.PositiveIntegerField(help_text='业务 code；响应非 JSON 时为 HTTP 状态码', verbose_name='状态码')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='调用次数')),
                ('cost_sum_ms', models.PositiveBigIntegerField(default=0, verbose_name='总耗时(毫秒)')),
                ('cost_max_ms', models.PositiveIntegerField(default=0, verbose_name='最大耗时(毫秒)')),
            ],
            options={
                'verbose_name': 'API调用统计',
                'verbose_name_plural': 'API调用统计',
                'db_table': 'api_call_stat',
                'ordering': ['-stat_date'],
                'indexes': [models.Index(fields=['service', 'stat_date'], name='idx_apistat_service_date'), models.Index(fields=['app_id', 'stat_date'], name='idx_apistat_app_date')],
                'constraints': [models.UniqueConstraint(fields=('stat_date', 'path', 'app_id', 'status_code'), name='uniq_api_call_stat')],
            },
        ),
    ]
