# Generated by Django 6.0.6 on 2026-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_open_captcha_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHostingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('capacity_bytes', models.BigIntegerField(default=52428800, verbose_name='容量（字节）')),
                ('used_bytes', models.BigIntegerField(default=0, verbose_name='已用（字节）')),
            ],
            options={
                'verbose_name': '图床Token',
                'verbose_name_plural': '图床Token',
                'db_table': 'image_hosting_token',
                'ordering': ['create_time', 'id'],
            },
        ),
    ]
