# Generated by Django 6.0.6 on 2026-09-27 00:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_image_hosting_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallStatHour',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='统计ID')),
                ('stat_date', models.DateField(help_text='按本地时区（Asia/Shanghai）日期切分', verbose_name='统计日期')),
                ('stat_hour', models.PositiveSmallIntegerField(help_text='本地时间小时 0-23', verbose_name='统计小时')),
                ('service', models.CharField(help_text='路径第 1 段，如 /api/email/', max_length=100, verbose_name='服务前缀')),
                ('path', models.CharField(help_text='不含查询串的请求路径', max_length=255, verbose_name='端点路径')),
                ('app_id', models.CharField(default='-', help_text='接入项目 APPID；开放接口与未认证请求记为 -', max_length=32, verbose_name='接入项目')),
                ('status_code', models.PositiveIntegerField(help_text='业务 code；响应非 JSON 时为 HTTP 状态码', verbose_name='状态码')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='调用次数')),
                ('cost_sum_ms', models.PositiveBigIntegerField(default=0, verbose_name='总耗时(毫秒)')),
                ('cost_max_ms', models.PositiveIntegerField(default=0, verbose_name='最大耗时(毫秒)')),
            ],
            options={
                'verbose_name': 'API调用统计(按小时)',
                'verbose_name_plural': 'API调用统计(按小时)',
                'db_table': 'api_call_stat_hour',
                'ordering': ['-stat_date', '-stat_hour'],
                'indexes': [models.Index(fields=['stat_date', 'stat_hour'], name='idx_apistat_hour_date'), models.Index(fields=['service', 'stat_date', 'stat_hour'], name='idx_apistat_hour_service'), models.Index(fields=['app_id', 'stat_date', 'stat_hour'], name='idx_apistat_hour_app')],
                'constraints': [models.UniqueConstraint(fields=('stat_date', 'stat_hour', 'path', 'app_id', 'status_code'), name='uniq_api_call_stat_hour')],
            },
        ),
    ]
