# Generated by Django 6.0.6 on 2026-09-27 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_api_call_stat_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverifyrecord',
            name='app',
            field=models.ForeignKey(blank=True, help_text='发起该次验证/注册请求的接入项目；历史数据为空，项目删除后置空（仅审计留痕）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verify_records', to='API.userapp', verbose_name='发起项目'),
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('method', models.CharField(choices=[('password', '账号/邮箱/手机号 + 密码'), ('code', '邮箱/手机号 + 验证码')], default='password', help_text='password=密码登录；code=验证码登录（免密码）', max_length=20, verbose_name='登录方式')),
                ('ip', models.CharField(blank=True, default='', help_text='客户端 IP；取不到时为空串', max_length=45, verbose_name='登录IP')),
                ('user_agent', models.CharField(blank=True, default='', help_text='User-Agent，截断到 255 字符', max_length=255, verbose_name='客户端')),
                ('app', models.ForeignKey(help_text='本次登录签发的 Token 所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='API.userapp', verbose_name='登录项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='API.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户登录日志',
                'verbose_name_plural': '用户登录日志',
                'db_table': 'user_login_log',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['user', 'app'], name='idx_login_log_user_app'), models.Index(fields=['user', '-create_time'], name='idx_login_log_user_time'), models.Index(fields=['app', '-create_time'], name='idx_login_log_app_time')],
            },
        ),
    ]
