# Generated by Django 6.0.6 on 2026-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_user_login_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiServicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('path_prefix', models.CharField(help_text='如 /api/user_center/users/ ，可精确到单个接口路径；请求路径按最长前缀匹配，优先于分类树', max_length=200, unique=True, verbose_name='URL前缀')),
                ('enabled', models.BooleanField(default=True, help_text='停用即该服务进入维护态：命中路径的 /api/ 请求统一返回「服务维护中」，不做签名校验', verbose_name='启用')),
                ('auth_mode', models.CharField(choices=[('inherit', '跟随分类树'), ('auth', '需要认证'), ('open', '开放')], default='inherit', help_text='inherit=跟随分类树；auth=需要认证；open=开放（无需认证）', max_length=10, verbose_name='认证模式')),
                ('app_scope', models.CharField(choices=[('all', '不限项目'), ('whitelist', '仅白名单项目')], default='all', help_text='all=不限项目；whitelist=仅白名单项目可调用（仅对「需要认证」的服务有意义）', max_length=10, verbose_name='项目范围')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('apps', models.ManyToManyField(blank=True, help_text='仅 app_scope=whitelist 时生效：名单内的项目才可调用该服务', related_name='service_policies', to='API.userapp', verbose_name='白名单项目')),
            ],
            options={
                'verbose_name': 'API服务策略',
                'verbose_name_plural': 'API服务策略',
                'ordering': ('path_prefix',),
            },
        ),
    ]
