# Generated by Django 6.0.6 on 2026-09-27 05:13
# 手工扩展：追加数据迁移 —— 把历史开放节点与手动状态搬进「服务策略」表，并退役分类树 / ServiceStatus

from django.db import migrations, models

# 必须保留为「开放」的服务级节点：
# - 登录 / 注册 / 重置密码页的图形验证码由浏览器直接访问，不带项目签名
#   （原分类树由迁移 0023_open_captcha_categories 置为 open）；
# - 调用统计是本站公开查询接口（文档与官网均声明免签名，见 API/website/docs/statistics.py）。
OPEN_NODES = (
    ('/api/captcha_self/', '自研图形验证码'),
    ('/api/captcha_auth/aliyun/', '阿里云图形认证'),
    ('/api/statistics/', '调用统计'),
)

# 旧 5 态 -> 新 4 态 映射
LEGACY_STATUS_MAP = {
    'open': 'normal',
    'testing': 'dev',
    'building': 'dev',
    'maintenance': 'maintenance',
    'offline': 'offline',
}


def migrate_legacy_status(apps, schema_editor):
    """数据迁移：分类树显式开放节点 + ServiceStatus 手动状态 -> 服务级策略；再固定已知开放节点"""
    ApiServicePolicy = apps.get_model('API', 'ApiServicePolicy')
    ApiCategory = apps.get_model('API', 'ApiCategory')
    ServiceStatus = apps.get_model('API', 'ServiceStatus')

    # 1) 保留分类树里显式设为 open 的节点（等价搬过来，避免历史开放服务被 fail-closed 拦死）
    for node in ApiCategory.objects.filter(status=True, auth_mode='open'):
        prefix = node.path_prefix
        depth = len([seg for seg in prefix.strip('/').split('/') if seg]) - 1  # 去掉前导 'api'
        level = 'service' if depth <= 1 else ('channel' if depth == 2 else 'endpoint')
        ApiServicePolicy.objects.update_or_create(
            path_prefix=prefix,
            defaults={'name': node.name or prefix, 'level': level, 'auth_mode': 'open',
                      'status': 'inherit', 'app_scope': 'inherit'},
        )

    # 2) 历史手动状态：按 url_prefix 建 / 更新对应的服务级策略 status
    for row in ServiceStatus.objects.all():
        mapped = LEGACY_STATUS_MAP.get(row.status)
        if not mapped:
            continue
        policy, created = ApiServicePolicy.objects.get_or_create(
            path_prefix=row.url_prefix,
            defaults={'name': row.url_prefix, 'level': 'service', 'status': mapped},
        )
        if not created:
            policy.status = mapped
            policy.save(update_fields=['status'])

    # 3) 已知开放节点（放在最后，保证其 auth_mode / status 不被上面的状态迁移覆盖）
    for prefix, name in OPEN_NODES:
        ApiServicePolicy.objects.update_or_create(
            path_prefix=prefix,
            defaults={'name': name, 'level': 'service', 'auth_mode': 'open',
                      'status': 'normal', 'app_scope': 'inherit'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_api_service_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='apiservicepolicy',
            name='enabled',
        ),
        migrations.AddField(
            model_name='apiservicepolicy',
            name='level',
            field=models.CharField(choices=[('service', '服务'), ('channel', '线路'), ('endpoint', '端点')], default='service', help_text='服务=整个服务；线路=服务下的某条线路；端点=精确到单个接口路径', max_length=10, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='apiservicepolicy',
            name='status',
            field=models.CharField(choices=[('inherit', '跟随上级'), ('normal', '正常'), ('dev', '开发中'), ('maintenance', '维护中'), ('offline', '已下线')], default='inherit', help_text='inherit=跟随上级；正常 / 开发中 / 维护中 / 已下线', max_length=12, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='apiservicepolicy',
            name='app_scope',
            field=models.CharField(choices=[('inherit', '跟随上级'), ('all', '不限项目'), ('whitelist', '仅白名单项目')], default='inherit', help_text='inherit=跟随上级；all=不限项目；whitelist=仅白名单项目可调用', max_length=10, verbose_name='项目范围'),
        ),
        migrations.AlterField(
            model_name='apiservicepolicy',
            name='apps',
            field=models.ManyToManyField(blank=True, help_text='仅生效值 app_scope=whitelist 时生效：名单内的项目才可调用', related_name='service_policies', to='API.userapp', verbose_name='白名单项目'),
        ),
        migrations.AlterField(
            model_name='apiservicepolicy',
            name='auth_mode',
            field=models.CharField(choices=[('inherit', '跟随上级'), ('auth', '需要签名'), ('open', '开放')], default='inherit', help_text='inherit=跟随上级；auth=需要签名；open=开放（无需签名）', max_length=10, verbose_name='认证模式'),
        ),
        migrations.AlterField(
            model_name='apiservicepolicy',
            name='path_prefix',
            field=models.CharField(help_text='服务级如 /api/movies/ ；线路级如 /api/movies/movie_555/ ；端点级如 /api/movies/movie_555/list', max_length=200, unique=True, verbose_name='URL前缀'),
        ),
        migrations.RunPython(migrate_legacy_status, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ServiceStatus',
        ),
        migrations.DeleteModel(
            name='ApiCategory',
        ),
    ]
