# Generated by Django 6.0.6 on 2026-09-28 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_service_policy_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HongguoEpisodeVideo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('series_id', models.CharField(db_index=True, max_length=32, verbose_name='剧集ID')),
                ('series_name', models.CharField(blank=True, default='', max_length=200, verbose_name='剧集名')),
                ('ep', models.PositiveIntegerField(verbose_name='集数')),
                ('url', models.URLField(max_length=1000, verbose_name='播放地址')),
                ('url_type', models.CharField(choices=[('mp4', 'MP4'), ('m3u8', 'M3U8')], default='mp4', help_text='mp4=直链文件；m3u8=HLS 播放列表', max_length=8, verbose_name='链接类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '红果短剧外链',
                'verbose_name_plural': '红果短剧外链',
                'db_table': 'hongguo_episode_video',
                'ordering': ['series_id', 'ep'],
                'constraints': [models.UniqueConstraint(fields=('series_id', 'ep'), name='uniq_hongguo_episode_video')],
            },
        ),
    ]
