# Generated by Django 6.0.6 on 2026-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_hongguo_episode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservicepolicy',
            name='audience',
            field=models.CharField(choices=[('inherit', '跟随上级'), ('normal', '正常'), ('admin_only', '仅专属管理员')], default='inherit', help_text='inherit=跟随上级；normal=对外正常可用；admin_only=仅专属管理员（仅后台内部使用，外部调用返回 20020）', max_length=12, verbose_name='使用范围'),
        ),
        migrations.AddField(
            model_name='apiservicepolicy',
            name='docs_visible',
            field=models.CharField(choices=[('inherit', '跟随上级'), ('visible', '文档展示'), ('hidden', '文档隐藏')], default='inherit', help_text='inherit=跟随上级；visible=展示在官网文档中心；hidden=在文档页与在线调试里隐藏（后台内部接口用）', max_length=10, verbose_name='文档可见性'),
        ),
    ]
