# Generated by Django 6.0.6 on 2026-09-29 02:58

import API.models.Projects.app
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_haijiao_image_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaijiaoAccount',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='账号ID')),
                ('user_id', models.CharField(db_index=True, help_text='海角社区的用户 ID（注册 / 登录接口返回），全局唯一', max_length=32, unique=True, verbose_name='源站用户ID')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='用户名')),
                ('password', API.models.Projects.app.EncryptedSecretField(help_text='落库 AES 加密存储（S-06）；接口不回传明文', max_length=200, verbose_name='密码')),
                ('email', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='邮箱')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('token', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='最近一次登录凭证，落库 AES 加密存储（S-06）', max_length=500, verbose_name='登录Token')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '海角社区账号',
                'verbose_name_plural': '海角社区账号',
                'db_table': 'haijiao_account',
                'ordering': ['-create_time'],
            },
        ),
    ]
