# Generated by Django 6.0.6 on 2026-09-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_haijiao_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='haijiaoaccount',
            name='last_sign_in_date',
            field=models.DateField(blank=True, help_text='每日金币签到的本地记录：等于当天即视为今日已签到，批量签到时直接跳过源站请求；跨天自动失效', null=True, verbose_name='最近签到日期'),
        ),
    ]
