# Generated by Django 6.0.6 on 2026-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_open_hongguo_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='原样展示（保留换行）；填什么语言就显示什么语言，不做翻译', verbose_name='正文')),
                ('level', models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '提醒'), ('error', '警告')], default='info', help_text='决定公告的配色与图标', max_length=10, verbose_name='级别')),
                ('scope', models.CharField(choices=[('service', '服务'), ('channel', '线路'), ('endpoint', '端点')], default='service', help_text='服务=整个服务；线路=该线路下所有接口；端点=单个接口路径', max_length=10, verbose_name='挂载层级')),
                ('path_prefix', models.CharField(db_index=True, help_text='服务级如 /api/dramas/ ；线路级如 /api/dramas/hongguo/ ；端点级如 /api/dramas/hongguo/play', max_length=200, verbose_name='URL前缀')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前（同层级内排序）', verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('start_time', models.DateTimeField(blank=True, help_text='留空表示立即生效', null=True, verbose_name='生效开始')),
                ('end_time', models.DateTimeField(blank=True, help_text='留空表示长期有效', null=True, verbose_name='生效结束')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '接口公告',
                'verbose_name_plural': '接口公告',
                'db_table': 'docs_announcement',
                'ordering': ('sort', 'create_time'),
            },
        ),
    ]
