# Generated by Django 6.0.6 on 2026-09-30 04:10

import API.models.Projects.app
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_docs_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.SlugField(help_text='英文小写标识，如 deepseek / moonshot / ark / dashscope；仅内部使用', max_length=30, unique=True, verbose_name='厂商标识')),
                ('name', models.CharField(help_text='后台与文档展示用，如「深度求索 DeepSeek」', max_length=50, verbose_name='厂商名称')),
                ('base_url', models.CharField(help_text='填到版本段为止（如 https://api.deepseek.com 或 https://api.moonshot.cn/v1），本服务会在其后拼 /chat/completions', max_length=200, verbose_name='上游根地址')),
                ('api_key', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='平台密钥；落库 AES 加密，页面只显示掩码', max_length=255, verbose_name='API Key')),
                ('key_hint', models.CharField(blank=True, help_text='保存时依据 Key 自动生成（如 sk-…4fe2），仅供后台辨认', max_length=32, verbose_name='Key 掩码')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后该厂商下所有模型不可用', verbose_name='启用')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'AI 厂商',
                'verbose_name_plural': 'AI 厂商',
                'db_table': 'ai_provider',
                'ordering': ('sort', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.SlugField(help_text='对外唯一标识，也是请求参数 model 的取值；建议与上游模型名一致', max_length=60, unique=True, verbose_name='模型标识')),
                ('upstream_name', models.CharField(blank=True, help_text='真正发给上游的模型名；留空则与「模型标识」相同', max_length=100, verbose_name='上游模型名')),
                ('name', models.CharField(help_text='后台与文档展示用', max_length=50, verbose_name='模型名称')),
                ('supports_vision', models.BooleanField(default=False, help_text='勾选后才允许请求携带 images；未勾选传图片会返回参数值非法', verbose_name='支持视觉（看图）')),
                ('context_window', models.IntegerField(blank=True, help_text='仅用于展示，可留空', null=True, verbose_name='上下文长度')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前（文档下拉顺序）', verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, help_text='下架后不在模型清单与文档下拉中出现', verbose_name='上架')),
                ('is_default', models.BooleanField(default=False, help_text='请求不传 model 时使用；全局应保持只有一个', verbose_name='默认模型')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='API.aiprovider', verbose_name='所属厂商')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'db_table': 'ai_model',
                'ordering': ('sort', 'key'),
            },
        ),
    ]
