# Generated by Django 6.0.6 on 2026-09-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_seed_ai_deepseek'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='后台辨认用，如「通用助手」「严格 JSON 输出」', max_length=50, verbose_name='提示词名称')),
                ('content', models.TextField(help_text='纯文本，作为 system 消息发给上游', verbose_name='提示词正文')),
                ('is_global', models.BooleanField(default=False, help_text='勾选后所有「跟随全局」的模型都用它；全局只保留一条', verbose_name='全局共享')),
                ('enabled', models.BooleanField(default=True, help_text='停用后视同不存在：指定它的模型会回落到全局共享那条', verbose_name='启用')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'AI 系统提示词',
                'verbose_name_plural': 'AI 系统提示词',
                'db_table': 'ai_system_prompt',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='max_tokens',
            field=models.IntegerField(blank=True, help_text='单次回复的 token 上限；留空=不下发该参数', null=True, verbose_name='最大回复长度'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='prompt_mode',
            field=models.CharField(choices=[('inherit', '跟随全局共享'), ('none', '不使用系统提示词'), ('custom', '指定提示词')], default='inherit', help_text='调用方自带 system_prompt 时以调用方为准，本项只在调用方没带时生效', max_length=10, verbose_name='系统提示词'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='stop',
            field=models.CharField(blank=True, help_text='JSON 数组（如 ["END","STOP"]）或纯文本（逗号/换行分隔）；留空=不下发', max_length=255, verbose_name='停止词'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='temperature',
            field=models.FloatField(blank=True, help_text='留空=不下发该参数，由上游默认值决定', null=True, verbose_name='采样温度'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='system_prompt',
            field=models.ForeignKey(blank=True, help_text='仅当系统提示词选择「指定提示词」时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_models', to='API.aisystemprompt', verbose_name='指定提示词'),
        ),
    ]
