# Generated by Django 6.0.6 on 2026-09-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0039_ai_prompt_and_sampling'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='max_images',
            field=models.PositiveSmallIntegerField(default=2, help_text='仅对支持视觉的模型生效；请求携带的 images 超过此数会返回参数值非法', verbose_name='最多图片数'),
        ),
    ]
