# Generated by Django 6.0.6 on 2026-09-30 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_ai_model_max_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.SlugField(help_text='英文小写标识，如 qq / qqmail / wechat / telegram；仅内部使用', max_length=30, unique=True, verbose_name='平台标识')),
                ('name', models.CharField(help_text='展示用，如「QQ」「Telegram」', max_length=30, verbose_name='平台名称')),
                ('icon', models.CharField(blank=True, help_text='lucide 图标名（如 message-circle / send），留空则只显示文字', max_length=30, verbose_name='图标')),
                ('value_label', models.CharField(blank=True, help_text='后台填值时的字段名，如「QQ 号」「微信号」「用户名」；留空则用「联系方式」', max_length=30, verbose_name='填写项名称')),
                ('url_template', models.CharField(blank=True, help_text='选填：把值拼成可点击链接，用 {value} 占位。如 https://t.me/{value}、mailto:{value}；必须以 http://、https://、mailto: 或 tel: 开头', max_length=200, verbose_name='跳转链接模板')),
                ('enabled', models.BooleanField(default=True, help_text='停用后不在前台展示（已填的值保留）', verbose_name='启用')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前（前台展示顺序）', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '联系方式平台',
                'verbose_name_plural': '联系方式平台',
                'db_table': 'contact_platform',
                'ordering': ('sort', 'code'),
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='附件ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10, verbose_name='类型')),
                ('path', models.CharField(help_text='相对 MEDIA_ROOT 的路径，如 uploads/feedback/20260930/xxx.png', max_length=255, verbose_name='文件路径')),
                ('original_name', models.CharField(blank=True, max_length=150, verbose_name='原始文件名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('ext', models.CharField(blank=True, help_text='小写，不含点', max_length=10, verbose_name='扩展名')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '反馈附件',
                'verbose_name_plural': '反馈附件',
                'db_table': 'feedback_attachment',
                'ordering': ('sort', 'create_time'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackAuditLog',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('kind', models.CharField(choices=[('submit', '提交内容审核'), ('reply', '回复语气审查')], default='submit', max_length=10, verbose_name='审核场景')),
                ('verdict', models.CharField(choices=[('pass', '通过'), ('reject', '驳回'), ('warn', '仅提醒'), ('error', '调用失败')], max_length=10, verbose_name='结论')),
                ('model_key', models.CharField(blank=True, max_length=60, verbose_name='审核模型')),
                ('reason', models.TextField(blank=True, help_text='AI 给出的理由要点原文', verbose_name='AI 意见')),
                ('forced', models.BooleanField(default=False, help_text='仅「回复语气审查」且 AI 有意见时可能为真', verbose_name='管理员强制发送')),
                ('operator', models.CharField(blank=True, help_text='管理员账号；提交审核时为空', max_length=150, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '反馈审核留痕',
                'verbose_name_plural': '反馈审核留痕',
                'db_table': 'feedback_audit_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReplyAttachment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='附件ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10, verbose_name='类型')),
                ('path', models.CharField(help_text='相对 MEDIA_ROOT 的路径，如 uploads/feedback/20260930/xxx.png', max_length=255, verbose_name='文件路径')),
                ('original_name', models.CharField(blank=True, max_length=150, verbose_name='原始文件名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('ext', models.CharField(blank=True, help_text='小写，不含点', max_length=10, verbose_name='扩展名')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '反馈回复附件',
                'verbose_name_plural': '反馈回复附件',
                'db_table': 'feedback_reply_attachment',
                'ordering': ('sort', 'create_time'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后前台反馈页停止服务（历史数据与后台仍可访问）', verbose_name='启用反馈中心')),
                ('ai_review_enabled', models.BooleanField(default=True, help_text='关闭后提交直接进入「待处理」；开启但平台未配置可用模型时同样跳过审核', verbose_name='提交时先过 AI 审核')),
                ('submit_prompt', models.TextField(blank=True, help_text='审核用户提交内容所用的规则。与问题正文、用户信息一起发给 AI，由 AI 判定是否驳回；留空则使用内置的通用审核规则（见文档中心「问题反馈中心」章节）', verbose_name='提交内容审核提示词')),
                ('reply_prompt', models.TextField(blank=True, help_text='管理员回复前审查所用规则（语气是否得体、是否有攻击性表述等）；留空则使用内置的通用审查规则。AI 只提醒，管理员仍可强制发送', verbose_name='回复语气审查提示词')),
                ('ai_reject_image', models.BooleanField(default=True, help_text='开启后 AI 只给驳回理由的要点，由本地绘图引擎渲染成中文说明图附在驳回内容里', verbose_name='AI 驳回时生成说明图')),
                ('max_images', models.PositiveSmallIntegerField(default=3, help_text='单条反馈 / 单条回复可携带的图片数量上限', verbose_name='图片张数上限')),
                ('max_videos', models.PositiveSmallIntegerField(default=1, help_text='单条反馈 / 单条回复可携带的视频数量上限', verbose_name='视频个数上限')),
                ('max_image_mb', models.PositiveSmallIntegerField(default=10, verbose_name='单张图片大小上限(MB)')),
                ('max_video_mb', models.PositiveSmallIntegerField(default=50, verbose_name='单个视频大小上限(MB)')),
                ('captcha_required', models.BooleanField(default=True, help_text='登录用户不受影响（身份可追溯）；关闭后游客可无验证码提交，仅靠频率限制兜底', verbose_name='游客提交需图形验证码')),
                ('rate_limit_hour', models.PositiveIntegerField(default=5, help_text='同一 IP 每小时最多提交多少条（防刷）', verbose_name='同 IP 每小时上限')),
                ('rate_limit_day', models.PositiveIntegerField(default=20, help_text='同一 IP 每天最多提交多少条（防刷）', verbose_name='同 IP 每天上限')),
                ('email_notify', models.BooleanField(default=True, help_text='管理员回复后，给提交时填了邮箱的那条发一封通知邮件（没填邮箱则不通知）', verbose_name='回复时发邮件通知')),
            ],
            options={
                'verbose_name': '反馈中心设置',
                'verbose_name_plural': '反馈中心设置',
                'db_table': 'feedback_setting',
            },
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.SlugField(help_text='英文小写标识，如 suggestion / upgrade / issue / bug / other；仅内部使用', max_length=30, unique=True, verbose_name='类型标识')),
                ('name', models.CharField(help_text='提交页与后台展示用，如「功能建议」', max_length=30, verbose_name='类型名称')),
                ('desc', models.CharField(blank=True, help_text='提交页类型选项下的一句话说明，可留空', max_length=100, verbose_name='类型说明')),
                ('icon', models.CharField(blank=True, help_text='lucide 图标名（如 lightbulb / bug），留空则只显示文字', max_length=30, verbose_name='图标')),
                ('is_default', models.BooleanField(default=False, help_text='提交页打开时默认选中的类型；全局只应保留一个', verbose_name='默认选中')),
                ('enabled', models.BooleanField(default=True, help_text='停用后不在提交页出现，历史反馈不受影响', verbose_name='启用')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前（提交页选项顺序）', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '反馈类型',
                'verbose_name_plural': '反馈类型',
                'db_table': 'feedback_type',
                'ordering': ('sort', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('value', models.CharField(help_text='该平台上的具体值，如 QQ 号 / 微信号 / 用户名', max_length=200, verbose_name='联系方式')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前（同一项目内排序）', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目联系方式',
                'verbose_name_plural': '项目联系方式',
                'db_table': 'project_contact',
                'ordering': ('sort', 'platform__sort'),
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-create_time'], 'verbose_name': '反馈', 'verbose_name_plural': '反馈'},
        ),
        migrations.AlterModelOptions(
            name='feedbackreply',
            options={'ordering': ['create_time'], 'verbose_name': '反馈回复', 'verbose_name_plural': '反馈回复'},
        ),
        migrations.RemoveIndex(
            model_name='feedbackreply',
            name='idx_freply_parent',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='idx_fb_app_status',
            old_name='idx_feedback_app_status',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='idx_fb_app_time',
            old_name='idx_feedback_app_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_unread',
            field=models.BooleanField(default=False, help_text='用户或游客跟帖后置位，管理员查看详情即清除', verbose_name='有新回复'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_checked_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 审核时间'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_model_key',
            field=models.CharField(blank=True, help_text='本条用的审核模型标识（留痕，模型可能被改名或删除）', max_length=60, verbose_name='审核模型'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_status',
            field=models.CharField(choices=[('skipped', '未开启审核'), ('pending', '待审核'), ('running', '审核中'), ('passed', '审核通过'), ('rejected', '审核驳回'), ('failed', '审核失败')], default='skipped', help_text='未开启审核 / 待审核 / 审核中 / 审核通过 / 审核驳回 / 审核失败', max_length=20, verbose_name='AI 审核状态'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='选填：游客或用户填了邮箱，管理员回复后会收到一封通知邮件', max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ip',
            field=models.CharField(blank=True, help_text='防滥用留痕', max_length=45, verbose_name='提交IP'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_reply_time',
            field=models.DateTimeField(blank=True, help_text='列表排序与「有新回复」提示用', null=True, verbose_name='最后回复时间'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='public_hidden',
            field=models.BooleanField(default=False, help_text='勾选后本条从公开区撤下（仅对游客提交的反馈有意义）', verbose_name='公开区隐藏'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.CharField(blank=True, help_text='防滥用留痕', max_length=255, verbose_name='提交UA'),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='admin_name',
            field=models.CharField(blank=True, help_text='超管回复时记录其登录账号，仅内部留痕、不对外展示', max_length=150, verbose_name='管理员账号'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='用户填写的正文（纯文本）', verbose_name='反馈内容'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('processing', '待处理'), ('replied', '已回复'), ('rejected', 'AI驳回'), ('closed', '已关闭')], default='pending', help_text='待审核 / 待处理 / 已回复 / AI驳回 / 已关闭', max_length=20, verbose_name='业务状态'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, help_text='登录用户提交时记录；游客（匿名）提交时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='API.user', verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='author_role',
            field=models.CharField(choices=[('user', '用户'), ('admin', '管理员'), ('ai', 'AI 审核')], default='user', help_text='user=用户跟帖 / admin=管理员 / ai=AI 审核', max_length=10, verbose_name='身份类型'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='content',
            field=models.TextField(help_text='回复正文（纯文本）', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='feedback',
            field=models.ForeignKey(help_text='回复归属于某条反馈；删除反馈会级联删除其全部回复', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='API.feedback', verbose_name='所属反馈'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='回复ID'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户跟帖时记录；管理员与 AI 回复时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_replies', to='API.user', verbose_name='跟帖用户'),
        ),
        migrations.AddIndex(
            model_name='feedbackreply',
            index=models.Index(fields=['feedback', 'create_time'], name='idx_freply_fb_time'),
        ),
        migrations.AddField(
            model_name='feedbackattachment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='API.feedback', verbose_name='所属反馈'),
        ),
        migrations.AddField(
            model_name='feedbackauditlog',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='API.feedback', verbose_name='所属反馈'),
        ),
        migrations.AddField(
            model_name='feedbackauditlog',
            name='reply',
            field=models.ForeignKey(blank=True, help_text='回复语气审查时指向被审查的那条回复；提交内容审核时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='API.feedbackreply', verbose_name='关联回复'),
        ),
        migrations.AddField(
            model_name='feedbackreplyattachment',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='API.feedbackreply', verbose_name='所属回复'),
        ),
        migrations.AddField(
            model_name='feedbacksetting',
            name='review_model',
            field=models.ForeignKey(blank=True, help_text='用于内容审核与回复审查；留空则使用平台默认模型。审核很吃调用量，建议单独指定一个便宜的模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='API.aimodel', verbose_name='审核专用模型'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.ForeignKey(blank=True, help_text='用户提交时选择的类型；类型被删除后历史反馈展示为「未分类」', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='API.feedbacktype', verbose_name='反馈类型'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['ai_status', 'create_time'], name='idx_fb_ai_queue'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='API.userapp', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='platform',
            field=models.ForeignKey(help_text='平台被删除前需先清掉各项目下的绑定（PROTECT 保护，避免误删导致前台联系方式整体消失）', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='API.contactplatform', verbose_name='联系方式平台'),
        ),
        migrations.RemoveField(
            model_name='feedbackreply',
            name='parent',
        ),
        migrations.AddConstraint(
            model_name='projectcontact',
            constraint=models.UniqueConstraint(fields=('app', 'platform'), name='uniq_project_contact'),
        ),
    ]
