# Generated by Django 6.0.6 on 2026-09-30 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_feedback_center_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='票据ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='票据')),
                ('expire_time', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('used', models.BooleanField(default=False, help_text='消费后置位；票据只能用一次', verbose_name='已使用')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='签发IP')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to='API.userapp', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to='API.user', verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '反馈页票据',
                'verbose_name_plural': '反馈页票据',
                'db_table': 'feedback_ticket',
                'ordering': ['-create_time'],
            },
        ),
    ]
