# Generated by Django 6.0.6 on 2026-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0043_feedback_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('preset', models.CharField(choices=[('aurora', '极光流彩'), ('terminal', '终端极客'), ('editorial', '编辑杂志'), ('neon', '霓虹赛博')], default='aurora', help_text='作用于官网首页与接口文档中心；颜色仍由访客选择的主题决定，二者互不冲突', max_length=20, verbose_name='视觉气质')),
                ('hero_badge', models.CharField(blank=True, help_text='Hero 标题上方的小标签，留空显示「通用 API 聚合服务平台」', max_length=40, verbose_name='首页徽标文案')),
                ('hero_title', models.CharField(blank=True, help_text='留空显示默认标题；可用 {n} 占位当前服务数量，如「一个平台，聚合 {n}+ 类能力」', max_length=60, verbose_name='首页主标题')),
                ('hero_subtitle', models.TextField(blank=True, help_text='留空显示默认副标题；同样支持 {n} 占位', verbose_name='首页副标题')),
            ],
            options={
                'verbose_name': '官网外观',
                'verbose_name_plural': '官网外观',
                'db_table': 'website_site_appearance',
            },
        ),
    ]
