# Generated by Django 6.0.6 on 2026-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0044_site_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservicepolicy',
            name='extra_prefixes',
            field=models.JSONField(blank=True, default=list, help_text='线路级多选时的其余线路前缀（须与主前缀同属一个服务）；与主前缀共同构成本策略覆盖的全部线路', verbose_name='附加线路前缀'),
        ),
    ]
