# Generated by Django 6.0.6 on 2026-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0045_policy_extra_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hide_console', models.BooleanField(default=True, help_text='开启后，未登录（或非超管）访问 /console/** 一律返回 404，与访问一个根本不存在的地址看起来完全一样，探测者无法据此判断后台是否存在；关闭则退回「跳转登录页」的行为，会把后台入口暴露出去', verbose_name='后台入口隐身')),
            ],
            options={
                'verbose_name': '安全设置',
                'verbose_name_plural': '安全设置',
                'db_table': 'security_setting',
            },
        ),
    ]
