# Generated by Django 6.0.6 on 2026-10-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0047_delete_hongguo_episode_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='与 API/apis/quota/services.py 的服务注册表一一对应', max_length=50, unique=True, verbose_name='服务标识')),
                ('balance', models.DecimalField(blank=True, decimal_places=4, help_text='最近一次成功检查取回的数值；从未成功过则为空', max_digits=14, null=True, verbose_name='当前余量')),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, help_text='余量低于该值时发通知；留空表示不通知', max_digits=14, null=True, verbose_name='最低数量阈值')),
                ('notify_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('notify_method', models.CharField(choices=[('email', '邮件')], default='email', help_text='目前只有邮件一种方式', max_length=20, verbose_name='通知方式')),
                ('alert_active', models.BooleanField(default=False, help_text='告警只发一次：跌破阈值时置位，恢复后自动复位（重新武装）', verbose_name='告警中')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('last_error', models.CharField(blank=True, default='', max_length=255, verbose_name='最近一次检查错误')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近告警时间')),
            ],
            options={
                'verbose_name': '服务余量',
                'verbose_name_plural': '服务余量',
                'db_table': 'quota_service',
            },
        ),
        migrations.CreateModel(
            name='QuotaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notify_email', models.EmailField(blank=True, default='', help_text='所有服务的余量告警统一发到该邮箱；留空则不发信，只在控制台提示告警', max_length=254, verbose_name='接收通知邮箱')),
            ],
            options={
                'verbose_name': '余量通知设置',
                'verbose_name_plural': '余量通知设置',
                'db_table': 'quota_setting',
            },
        ),
    ]
