# Generated by Django 6.0.6 on 2026-10-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0048_quota_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(blank=True, default='', help_text='超管用户名（冗余保存：账号改名 / 删除后仍可追溯）', max_length=64, verbose_name='操作者')),
                ('operator_id', models.BigIntegerField(blank=True, help_text='Django 超管账号主键（不做外键，避免删号牵连审计记录）', null=True, verbose_name='操作者ID')),
                ('method', models.CharField(max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('view_name', models.CharField(blank=True, default='', help_text='解析出的 URL name，如 console_services', max_length=120, verbose_name='功能')),
                ('action', models.CharField(blank=True, default='', help_text='表单里的 action 字段，如 create / edit / delete', max_length=64, verbose_name='动作')),
                ('target', models.CharField(blank=True, default='', help_text='表单里的 id 等目标标识', max_length=120, verbose_name='操作对象')),
                ('note', models.CharField(blank=True, default='', help_text='视图给出的可读说明（与操作者看到的成功提示同一句）；未提供时为空', max_length=255, verbose_name='说明')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('ip', models.CharField(blank=True, default='', max_length=45, verbose_name='来源 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': '控制台操作日志',
                'verbose_name_plural': '控制台操作日志',
                'db_table': 'console_audit_log',
                'ordering': ('-create_time',),
                'indexes': [models.Index(fields=['-create_time'], name='console_audit_time_idx')],
            },
        ),
    ]
