# Generated by Django 6.0.6 on 2026-10-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0049_console_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamAlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后不再判定与发送上游故障告警；已置位的告警态会在下一轮检查时复位', verbose_name='启用告警')),
                ('failed_rate_threshold', models.DecimalField(decimal_places=2, default=50, help_text='窗口内上游错误占比不低于该百分比（%）时告警', max_digits=5, verbose_name='失败率阈值')),
                ('min_calls', models.PositiveIntegerField(default=20, help_text='窗口内总调用量低于该值时不判定，避免小样本误报', verbose_name='最小样本数')),
            ],
            options={
                'verbose_name': '上游故障告警设置',
                'verbose_name_plural': '上游故障告警设置',
                'db_table': 'upstream_alert_setting',
            },
        ),
        migrations.CreateModel(
            name='UpstreamAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('service', models.CharField(help_text='与调用统计表的 service 字段口径一致，如 /api/haijiao/', max_length=64, unique=True, verbose_name='服务前缀')),
                ('alert_active', models.BooleanField(default=False, help_text='告警只发一次：判定为故障时置位，恢复正常后自动复位（重新武装）', verbose_name='告警中')),
                ('last_alert_at', models.DateTimeField(blank=True, null=True, verbose_name='最近告警时间')),
            ],
            options={
                'verbose_name': '上游故障告警态',
                'verbose_name_plural': '上游故障告警态',
                'db_table': 'upstream_alert_state',
                'ordering': ('service',),
            },
        ),
    ]
