# Generated by Django 6.0.6 on 2026-10-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0050_monitor_upstream_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='daily_limit',
            field=models.PositiveBigIntegerField(blank=True, help_text='每个自然日（本地时区）允许的调用次数；留空表示不限制', null=True, verbose_name='每日调用上限'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='monthly_limit',
            field=models.PositiveBigIntegerField(blank=True, help_text='每个自然月（本地时区）允许的调用次数；留空表示不限制', null=True, verbose_name='每月调用上限'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='项目归属的注册用户，可在前台「我的项目」自助管理；留空表示平台自有项目，只有超管能管', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apps', to='API.user', verbose_name='归属用户'),
        ),
    ]
