# Generated by Django 6.0.6 on 2026-10-02 02:57

from django.db import migrations, models


def carry_over_prices(apps, schema_editor):
    """把旧 ApiServicePolicy.price 上已配置的单价搬到独立的 ApiPricePolicy

    0053 才给策略表加了 price（控制台可配），若已有非空值，按同一 URL 前缀与层级
    原样搬进新表，避免升级时丢配置。没有任何配置时不做任何事。
    """
    Policy = apps.get_model('API', 'ApiServicePolicy')
    Price = apps.get_model('API', 'ApiPricePolicy')
    for row in Policy.objects.exclude(price__isnull=True):
        Price.objects.update_or_create(
            path_prefix=row.path_prefix,
            defaults={'level': row.level, 'price': row.price},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0053_credit_ledger_remove_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.CharField(choices=[('service', '服务'), ('channel', '线路'), ('endpoint', '端点')], default='service', help_text='服务=整个服务；线路=服务下的某条线路；端点=精确到单个接口路径', max_length=10, verbose_name='层级')),
                ('path_prefix', models.CharField(help_text='服务级如 /api/movies/ ；线路级如 /api/movies/movie_555/ ；端点级如 /api/movies/movie_555/list', max_length=200, unique=True, verbose_name='URL前缀')),
                ('price', models.DecimalField(decimal_places=4, help_text='调用成功一次扣的点数；0 表示该节点免费', max_digits=12, verbose_name='单价（点/次）')),
            ],
            options={
                'verbose_name': 'API 调用单价',
                'verbose_name_plural': 'API 调用单价',
                'db_table': 'api_price_policy',
                'ordering': ('path_prefix',),
            },
        ),
        # 先搬数据，再删旧字段（顺序不能颠倒）
        migrations.RunPython(carry_over_prices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='apiservicepolicy',
            name='price',
        ),
        migrations.AddField(
            model_name='apicallstat',
            name='cost_points',
            field=models.DecimalField(decimal_places=4, default=0, help_text='成功调用按当时生效单价结算的点数（失败调用记 0）', max_digits=20, verbose_name='消耗点数'),
        ),
        migrations.AddField(
            model_name='apicallstathour',
            name='cost_points',
            field=models.DecimalField(decimal_places=4, default=0, help_text='成功调用按当时生效单价结算的点数（失败调用记 0）', max_digits=20, verbose_name='消耗点数'),
        ),
    ]
