# Generated by Django 6.0.6 on 2026-10-02 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0054_credit_price_and_cost_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='与 providers 注册表 key 一致，如 ezfp', max_length=32, unique=True, verbose_name='渠道标识')),
                ('name', models.CharField(help_text='后台展示名，如「易支付」', max_length=64, verbose_name='渠道名称')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='启用')),
                ('merchant_id', models.CharField(blank=True, default='', help_text='易支付即 pid；参与签名，务必与商户后台一致', max_length=64, verbose_name='商户ID')),
                ('private_key_enc', models.TextField(blank=True, default='', help_text='后台填写明文，入库自动加密；页面不回显，留空表示不修改', verbose_name='商户私钥（密文）')),
                ('platform_public_key_enc', models.TextField(blank=True, default='', help_text='用于校验平台返回与异步通知签名；同样加密落库', verbose_name='平台公钥（密文）')),
                ('gateway', models.CharField(blank=True, default='', help_text='留空使用内置默认地址（如 https://www.ezfp.cn），便于切换测试环境', max_length=200, verbose_name='网关地址')),
                ('enabled_methods', models.CharField(blank=True, default='', help_text='逗号分隔，如 alipay,wxpay；留空表示该渠道全部支付方式可用', max_length=200, verbose_name='允许的支付方式')),
                ('sort', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '支付渠道',
                'verbose_name_plural': '支付渠道',
                'db_table': 'pay_provider',
                'ordering': ('sort', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后前台充值页不再展示下单入口，/api/pay/create 直接返回「支付未开启」', verbose_name='开启在线支付')),
                ('points_per_yuan', models.DecimalField(decimal_places=4, default=1, help_text='1 元等于多少点数，用于「用户余额（元）→ 接入项目点数」的兑换；默认 1', max_digits=12, verbose_name='兑换汇率（点/元）')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, help_text='单笔充值 / 下单的最低金额，低于该值直接拒绝', max_digits=14, verbose_name='单笔最低金额（元）')),
            ],
            options={
                'verbose_name': '支付设置',
                'verbose_name_plural': '支付设置',
                'db_table': 'pay_setting',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='账户余额（元，两位小数）；由支付充值 / 管理员调整变动，可按汇率兑换成接入项目点数（见 API/models/Payment/）', max_digits=14, verbose_name='账户余额'),
        ),
        migrations.CreateModel(
            name='PayNotifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider_code', models.CharField(db_index=True, max_length=32, verbose_name='支付渠道')),
                ('out_trade_no', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='商户订单号')),
                ('trade_no', models.CharField(blank=True, default='', max_length=64, verbose_name='平台订单号')),
                ('raw', models.TextField(blank=True, default='', help_text='平台发来的原始参数串（含 sign）', verbose_name='通知原文')),
                ('verified', models.BooleanField(default=False, verbose_name='验签通过')),
                ('handled', models.BooleanField(default=False, help_text='True = 本次通知成功推进了订单状态（含「已处理过、幂等跳过」）', verbose_name='业务已处理')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='处理结果')),
                ('ip', models.CharField(blank=True, default='', max_length=45, verbose_name='来源IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': '支付回调留痕',
                'verbose_name_plural': '支付回调留痕',
                'db_table': 'pay_notify_log',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['out_trade_no', '-create_time'], name='idx_pay_notify_order_time')],
            },
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('out_trade_no', models.CharField(help_text='本系统生成，全局唯一；传给支付平台作为 out_trade_no', max_length=64, unique=True, verbose_name='商户订单号')),
                ('trade_no', models.CharField(blank=True, db_index=True, default='', help_text='支付平台返回的订单号（下单时可能还没有，回调/查单补齐）', max_length=64, verbose_name='平台订单号')),
                ('provider_code', models.CharField(db_index=True, help_text='PayProvider.code，如 ezfp', max_length=32, verbose_name='支付渠道')),
                ('pay_type', models.CharField(blank=True, default='', help_text='alipay / wxpay …', max_length=20, verbose_name='支付方式')),
                ('method', models.CharField(blank=True, default='web', help_text='易支付的 method，本站固定 web（只取二维码）', max_length=20, verbose_name='发起方式')),
                ('subject', models.CharField(help_text='传给平台的 name', max_length=128, verbose_name='商品名称')),
                ('amount', models.DecimalField(decimal_places=2, help_text='两位小数；回调时必须与本字段核对', max_digits=14, verbose_name='订单金额（元）')),
                ('pay_info', models.TextField(blank=True, default='', help_text='平台返回的 pay_info（本系统只用二维码内容），供前端展示', verbose_name='支付参数')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('partial_refunded', '部分退款'), ('refunded', '已全额退款'), ('failed', '支付失败'), ('closed', '已关闭')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已退款金额（元）')),
                ('buyer', models.CharField(blank=True, default='', max_length=128, verbose_name='支付用户标识')),
                ('client_ip', models.CharField(blank=True, default='', max_length=45, verbose_name='用户IP')),
                ('param', models.CharField(blank=True, default='', help_text='调用方传入，回调/查单原样返回，便于对账', max_length=255, verbose_name='业务扩展参数')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('last_query_at', models.DateTimeField(blank=True, null=True, verbose_name='最近查单时间')),
                ('app', models.ForeignKey(blank=True, help_text='对外调用时签名认证出的接入项目；本站充值订单为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_orders', to='API.userapp', verbose_name='下单项目')),
                ('user', models.ForeignKey(blank=True, help_text='本站充值订单的下单用户；对外调用创建的订单为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_orders', to='API.user', verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'pay_order',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserBalanceLedger',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='流水ID')),
                ('type', models.CharField(choices=[('pay', '支付充值'), ('transfer', '兑换项目点数'), ('admin', '管理员调整'), ('refund', '退款扣回')], db_index=True, max_length=20, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数=余额增加，负数=余额减少', max_digits=14, verbose_name='变动金额（元）')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='变动后余额（元）')),
                ('points', models.DecimalField(decimal_places=4, default=0, help_text='仅兑换类型有意义：本次换到项目上的点数', max_digits=20, verbose_name='兑换点数')),
                ('operator', models.CharField(blank=True, default='', help_text='管理员调整时记超管用户名；系统动作为空', max_length=64, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('app', models.ForeignKey(blank=True, help_text='兑换项目点数时的目标项目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_ledgers', to='API.userapp', verbose_name='关联项目')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_ledgers', to='API.payorder', verbose_name='关联支付订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_ledgers', to='API.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户余额流水',
                'verbose_name_plural': '用户余额流水',
                'db_table': 'user_balance_ledger',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='payorder',
            index=models.Index(fields=['provider_code', 'status'], name='idx_pay_order_prov_status'),
        ),
        migrations.AddIndex(
            model_name='payorder',
            index=models.Index(fields=['user', '-create_time'], name='idx_pay_order_user_time'),
        ),
        migrations.AddIndex(
            model_name='payorder',
            index=models.Index(fields=['app', '-create_time'], name='idx_pay_order_app_time'),
        ),
        migrations.AddIndex(
            model_name='userbalanceledger',
            index=models.Index(fields=['user', '-create_time'], name='idx_user_bal_user_time'),
        ),
        migrations.AddIndex(
            model_name='userbalanceledger',
            index=models.Index(fields=['type', '-create_time'], name='idx_user_bal_type_time'),
        ),
    ]
