# Generated by Django 6.0.6 on 2026-10-02 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0058_pay_rate_two_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('ip', models.CharField(db_index=True, help_text='被封禁的客户端 IP（兼容 IPv4 / IPv6）', max_length=45, verbose_name='IP 地址')),
                ('reason', models.CharField(help_text='必填；会展示给被封禁的访客与管理员，便于申诉与复核', max_length=255, verbose_name='封禁原因')),
                ('expire_time', models.DateTimeField(blank=True, db_index=True, help_text='到期后自动失效；留空表示永久封禁', null=True, verbose_name='封禁到期')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='手动解禁会置为 False；与「是否到期」无关', verbose_name='封禁中')),
                ('operator', models.CharField(blank=True, default='', help_text='发起封禁的控制台账号', max_length=64, verbose_name='操作人')),
                ('unbanned_at', models.DateTimeField(blank=True, null=True, verbose_name='解禁时间')),
                ('unban_note', models.CharField(blank=True, default='', max_length=255, verbose_name='解禁备注')),
            ],
            options={
                'verbose_name': 'IP 封禁',
                'verbose_name_plural': 'IP 封禁',
                'db_table': 'banned_ip',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['ip', 'is_active'], name='idx_banned_ip_active'), models.Index(fields=['expire_time'], name='idx_banned_ip_expire')],
            },
        ),
    ]
