# Generated by Django 6.0.6 on 2026-10-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0061_ai_model_audio_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiPricePolicy',
        ),
        migrations.RemoveIndex(
            model_name='appcreditledger',
            name='idx_credit_app_time',
        ),
        migrations.RemoveField(
            model_name='apicallstat',
            name='cost_points',
        ),
        migrations.RemoveField(
            model_name='apicallstathour',
            name='cost_points',
        ),
        migrations.RemoveField(
            model_name='paysetting',
            name='points_per_yuan',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userbalanceledger',
            name='app',
        ),
        migrations.RemoveField(
            model_name='userbalanceledger',
            name='points',
        ),
        migrations.AlterField(
            model_name='payorder',
            name='app',
            field=models.ForeignKey(blank=True, help_text='对外调用时签名认证出的接入项目（用于归属隔离）；本站充值订单为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_orders', to='API.userapp', verbose_name='下单项目'),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='钱最终加到这个用户的账户余额上；本站充值即下单人，对外调用由调用方用 user_id 指定', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_orders', to='API.user', verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='账户余额（元，两位小数）；由支付充值 / 管理员调整 / 退款扣回变动', max_digits=14, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='userbalanceledger',
            name='type',
            field=models.CharField(choices=[('pay', '支付充值'), ('admin', '管理员调整'), ('refund', '退款扣回')], db_index=True, max_length=20, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='AppCreditLedger',
        ),
    ]
