# Generated by Django 6.0.6 on 2026-10-02 10:08

"""下线「上游故障告警」模块

删除 `upstream_alert_setting`（阈值 / 开关单例）与 `upstream_alert_state`
（按服务的告警武装状态）两张表 —— 巡检线程、控制台页 `/console/upstreams/`、
侧边栏入口与回归脚本已一并移除，无需任何后续操作。
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0062_drop_credit_price_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpstreamAlertSetting',
        ),
        migrations.DeleteModel(
            name='UpstreamAlertState',
        ),
    ]
