# Generated by Django 6.0.6 on 2026-10-02 23:18

import API.models.Projects.app
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0063_drop_upstream_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='账号ID')),
                ('platform', models.CharField(choices=[('zhihu', '知乎'), ('xiaohongshu', '小红书'), ('weibo', '微博'), ('baijiahao', '百家号'), ('toutiao', '今日头条'), ('other', '其他')], db_index=True, default='zhihu', max_length=32, verbose_name='平台')),
                ('account', models.CharField(db_index=True, help_text='用户名 / 手机号 / 邮箱 / 备注名，同一平台内唯一', max_length=128, verbose_name='账号标识')),
                ('password', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='落库 AES 加密存储（S-06）；页面与接口均不回显明文', max_length=500, verbose_name='密码')),
                ('credential', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='Cookie 等登录凭据（原样一整串），落库 AES 加密存储（S-06）；爬虫接口用的就是它', max_length=8000, verbose_name='登录凭据')),
                ('status', models.CharField(choices=[('unknown', '未校验'), ('valid', '有效'), ('expired', '已过期（需重新登录）')], db_index=True, default='unknown', max_length=16, verbose_name='凭据状态')),
                ('check_message', models.CharField(blank=True, max_length=255, verbose_name='最近校验结果')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最近校验时间')),
                ('last_login_time', models.DateTimeField(blank=True, help_text='最近一次「人工登录后更新凭据」的时间', null=True, verbose_name='最近登录时间')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '平台账号',
                'verbose_name_plural': '平台账号',
                'db_table': 'platform_account',
                'ordering': ['platform', 'account'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'account'), name='uniq_platform_account')],
            },
        ),
    ]
