# Generated by Django 6.0.6 on 2026-10-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0065_open_weibo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.CharField(choices=[('zhihu', '知乎'), ('xiaohongshu', '小红书'), ('weibo', '微博'), ('baijiahao', '百家号'), ('toutiao', '今日头条'), ('dlt', '代练通'), ('other', '其他')], db_index=True, default='zhihu', max_length=32, verbose_name='平台'),
        ),
    ]
