# Generated by Django 6.0.6 on 2026-10-04 22:58

import API.models.Projects.app
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0067_alter_platformaccount_platform_dlwz'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMigration',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('dlt_serial_no', models.CharField(max_length=64, unique=True, verbose_name='代练通订单号')),
                ('dlt_title', models.CharField(max_length=255, verbose_name='代练通标题')),
                ('dlt_price', models.FloatField(verbose_name='代练通金额(元)')),
                ('dlt_zone', models.CharField(max_length=32, verbose_name='代练通大区')),
                ('dlt_time_limit', models.IntegerField(verbose_name='代练通时限(小时)')),
                ('dlwz_trade_no', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='丸子订单号')),
                ('amount', models.FloatField(default=0, verbose_name='丸子发布价(元)')),
                ('security_deposit', models.FloatField(default=0, verbose_name='安全保证金(元)')),
                ('efficiency_deposit', models.FloatField(default=0, verbose_name='效率保证金(元)')),
                ('status', models.CharField(choices=[('candidate', '已抓取（未发布）'), ('published', '已发丸子（待接单）'), ('taken', '代练通已接单'), ('failed', '失败'), ('cancelled', '已撤单')], db_index=True, default='candidate', max_length=16, verbose_name='状态')),
                ('dlwz_status', models.IntegerField(blank=True, null=True, verbose_name='丸子订单状态快照')),
                ('account_info', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='代练通接单后取到的账号/密码/角色名等，落库 AES 加密', max_length=2000, verbose_name='号主账号信息')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='备注/错误')),
            ],
            options={
                'verbose_name': '代练搬单记录',
                'verbose_name_plural': '代练搬单记录',
                'db_table': 'order_migration',
                'ordering': ['-create_time'],
            },
        ),
    ]
