# Generated by Django 6.0.6 on 2026-10-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0068_ordermigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMigrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('our_qq', models.CharField(blank=True, default='', help_text='发单时填入代练丸子的账号 / 密码 / 角色名与联系方式，引导打手加好友后私下交接账号', max_length=32, verbose_name='我们的 QQ 号')),
                ('interval_seconds', models.PositiveIntegerField(default=20, help_text='监控丸子「被接单」的轮询间隔，最小 5 秒', verbose_name='轮询间隔(秒)')),
                ('publish_limit', models.PositiveIntegerField(default=1, help_text='每轮最多发布到代练丸子的订单数', verbose_name='每轮发布上限')),
                ('price_min', models.FloatField(blank=True, help_text='只搬 >= 该价的代练通订单；留空不限', null=True, verbose_name='价格下限(元)')),
                ('price_max', models.FloatField(blank=True, help_text='只搬 <= 该价的代练通订单；留空不限', null=True, verbose_name='价格上限(元)')),
                ('auto_run', models.BooleanField(default=False, help_text='开启后后台线程按间隔自动执行搬单流水线（会真实发单 / 接单，谨慎开启）', verbose_name='自动运行')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间')),
                ('last_run_summary', models.CharField(blank=True, max_length=255, verbose_name='最近运行结果')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='最近错误')),
            ],
            options={
                'verbose_name': '代练搬单设置',
                'verbose_name_plural': '代练搬单设置',
                'db_table': 'order_migration_setting',
            },
        ),
    ]
