# Generated by Django 6.0.6 on 2026-10-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0069_ordermigrationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='keyword',
            field=models.CharField(blank=True, default='', help_text='只搬标题包含该关键词的代练通订单；留空则不限（用于自测时精确只搬自己发的单）', max_length=64, verbose_name='标题关键词'),
        ),
    ]
