# Generated by Django 6.0.6 on 2026-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0070_ordermigrationsetting_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='price_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='丸子发单的曝光档位下标（取自 slicePriceCal 的 categoryPriceList）：0=普通服务 1=俱乐部服务(严选，要求打手等级≥2) 2=悬赏区服务(仅签约打手可接)', verbose_name='服务档位(曝光)'),
        ),
    ]
