# Generated by Django 6.0.6 on 2026-10-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0071_ordermigrationsetting_price_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='take_level',
            field=models.SmallIntegerField(default=-1, help_text='丸子发单的接单门槛：-1=不限(标准，低等级打手可接) 0=Lv1以上 1=Lv2以上(严选)。不设置会沿用平台默认（严选，打手需 Lv2+）', verbose_name='接单门槛(代练师等级)'),
        ),
    ]
