# Generated by Django 6.0.6 on 2026-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0072_ordermigrationsetting_take_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermigrationsetting',
            name='price_index',
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='use_tier',
            field=models.BooleanField(default=False, help_text='关闭=标准（category=1，与丸子 App 默认一致，低等级打手可接）；开启=严选（带 slicePriceCal 服务档位，category=12，要求打手 Lv2+）', verbose_name='严选发单'),
        ),
    ]
