# Generated by Django 6.0.6 on 2026-10-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0073_remove_ordermigrationsetting_price_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='revoke_image',
            field=models.CharField(blank=True, default='', help_text='抢接失败需「申请撤销」时的凭证图片URL（丸子强制要求至少一张）；留空则取消不了时只告警、不自动撤销', max_length=500, verbose_name='撤销凭证图URL'),
        ),
    ]
