# Generated by Django 6.0.6 on 2026-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0074_ordermigrationsetting_revoke_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_mail',
            field=models.BooleanField(default=False, help_text='代练丸子有打手接单时，发一封邮件通知', verbose_name='被接单邮件通知'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_mail_to',
            field=models.EmailField(blank=True, default='', help_text='被接单邮件的收件人；留空则用 .env 的 QQ_MAIL_ACCOUNT', max_length=254, verbose_name='通知邮箱'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_sound',
            field=models.BooleanField(default=False, help_text='代练丸子有打手接单时，在本机（服务器）播放语音提醒', verbose_name='被接单声音提醒'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_sound_file',
            field=models.CharField(blank=True, default='', help_text='已生成的语音文件路径（自动维护，无需手填）', max_length=255, verbose_name='声音文件'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_sound_text',
            field=models.CharField(blank=True, default='丸子来新订单了', help_text='语音提醒内容；文本变更后会自动重新生成音频', max_length=100, verbose_name='声音文本'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='title_blacklist',
            field=models.TextField(blank=True, default='r\n此单\n联系\n看要求\n出w\nw\n出\n需要\n老板\n接\n人不够\n俱乐部\n限\n陪练\n陪\n勿扰\n一个', help_text='每行一个词；代练通标题包含任意一个词就不搬运（避免标题像公告被平台判定）', verbose_name='标题黑名单'),
        ),
    ]
