# Generated by Django 6.0.6 on 2026-10-05 06:00

from django.db import migrations, models

# 初始黑名单（与需求给的数组一致）；数据迁移不 import 应用代码，故在此复写一份
DEFAULT_WORDS = [
    'r', '此单', '联系', '看要求', '出w', 'w', '出', '需要', '老板',
    '接', '人不够', '俱乐部', '限', '陪练', '陪', '勿扰', '一个',
]


def seed_blacklist(apps, schema_editor):
    """把配置里原有的「标题黑名单」文本拆成逐条记录（为空则写入默认 17 条）"""
    Setting = apps.get_model('API', 'OrderMigrationSetting')
    Blacklist = apps.get_model('API', 'OrderMigrationBlacklist')

    raw = ''
    setting = Setting.objects.filter(pk=1).first()
    if setting is not None:
        raw = (setting.title_blacklist or '').strip()
    words = [w.strip() for w in raw.splitlines() if w.strip()] if raw else DEFAULT_WORDS

    seen = set()
    for word in words:
        if word not in seen:
            seen.add(word)
            Blacklist.objects.create(word=word)


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0075_ordermigrationsetting_notify_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMigrationBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('word', models.CharField(max_length=64, unique=True, verbose_name='黑名单词')),
            ],
            options={
                'verbose_name': '搬单标题黑名单',
                'verbose_name_plural': '搬单标题黑名单',
                'db_table': 'order_migration_blacklist',
                'ordering': ['-create_time'],
            },
        ),
        # 先建表并灌数据，再删掉配置里的文本字段
        migrations.RunPython(seed_blacklist, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ordermigrationsetting',
            name='notify_sound_file',
        ),
        migrations.RemoveField(
            model_name='ordermigrationsetting',
            name='title_blacklist',
        ),
        migrations.AlterField(
            model_name='ordermigrationsetting',
            name='notify_sound',
            field=models.BooleanField(default=False, help_text='代练丸子有打手接单时，由后台页面用浏览器语音播报提醒（页面需打开）', verbose_name='被接单声音提醒'),
        ),
        migrations.AlterField(
            model_name='ordermigrationsetting',
            name='notify_sound_text',
            field=models.CharField(blank=True, default='丸子来新订单了', help_text='浏览器语音播报的内容', max_length=100, verbose_name='声音文本'),
        ),
    ]
