# Generated by Django 6.0.6 on 2026-10-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0076_ordermigrationblacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='deposit_ratio',
            field=models.PositiveSmallIntegerField(default=2, help_text='丸子双金（安全保证金 + 效率保证金合计）= 发布价 × 该倍数，可设 0-5，默认 2；两项均分，即各 = 发布价 × 倍数 ÷ 2', verbose_name='双金倍数'),
        ),
    ]
