# Generated by Django 6.0.6 on 2026-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0077_ordermigrationsetting_deposit_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigration',
            name='dlt_ensure',
            field=models.FloatField(default=0, help_text='该代练通原单接单需冻结的总保证金（Ensure），用于跨轮占用代练通余额、防止超发', verbose_name='代练通双金(元)'),
        ),
    ]
