# Generated by Django 6.0.6 on 2026-10-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0078_ordermigration_dlt_ensure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='run_logs',
            field=models.TextField(blank=True, default='', help_text='最近若干轮运行结果的滚动日志（JSON 文本），供后台页实时展示', verbose_name='运行日志'),
        ),
    ]
