# Generated by Django 6.0.6 on 2026-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0079_ordermigrationsetting_run_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermigration',
            name='status',
            field=models.CharField(choices=[('candidate', '已抓取（未发布）'), ('publishing', '发单中（未确认）'), ('published', '已发丸子（待接单）'), ('taken', '代练通已接单'), ('failed', '失败'), ('cancelled', '已撤单')], db_index=True, default='candidate', max_length=16, verbose_name='状态'),
        ),
    ]
