# Generated by Django 6.0.6 on 2026-10-05 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0080_alter_ordermigration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('channel', models.CharField(db_index=True, default='serverchan', help_text='线路标识（如 serverchan = Server酱）', max_length=32, verbose_name='推送渠道')),
                ('app_id', models.CharField(blank=True, db_index=True, help_text='发起调用的接入项目 APPID（未认证时为空）', max_length=64, verbose_name='调用项目')),
                ('title', models.CharField(max_length=255, verbose_name='消息标题')),
                ('content', models.TextField(blank=True, verbose_name='消息正文')),
                ('ok', models.BooleanField(db_index=True, default=False, help_text='上游返回 code=0 视为成功', verbose_name='是否成功')),
                ('code', models.IntegerField(blank=True, help_text='上游接口返回的 code；网络异常等未取到时为空', null=True, verbose_name='上游返回码')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='结果说明')),
                ('pushid', models.CharField(blank=True, help_text='上游返回的 pushid（成功时用于在 Server酱 后台定位这条消息）', max_length=64, verbose_name='推送ID')),
            ],
            options={
                'verbose_name': '推送日志',
                'verbose_name_plural': '推送日志',
                'db_table': 'push_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.CharField(choices=[('zhihu', '知乎'), ('xiaohongshu', '小红书'), ('weibo', '微博'), ('baijiahao', '百家号'), ('toutiao', '今日头条'), ('dlt', '代练通'), ('dlwz', '代练丸子'), ('serverchan', 'Server酱'), ('other', '其他')], db_index=True, default='zhihu', max_length=32, verbose_name='平台'),
        ),
    ]
