# Generated by Django 6.0.6 on 2026-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0081_pushlog_alter_platformaccount_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushlog',
            name='recipients',
            field=models.CharField(blank=True, help_text='邮件收件人（多个用逗号分隔）；Server酱 推送等无收件人的渠道为空', max_length=1000, verbose_name='收件人'),
        ),
    ]
