# Generated by Django 6.0.6 on 2026-10-05 22:19

import API.models.Projects.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0082_pushlog_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qqbot_api_base', models.CharField(blank=True, default='', help_text='NapCat「网络配置」里 HTTP 服务端的地址，例如 http://127.0.0.1:3000；留空则该线路不可用', max_length=200, verbose_name='QQBot HTTP 地址')),
                ('qqbot_token', API.models.Projects.app.EncryptedSecretField(blank=True, help_text='NapCat HTTP 服务端里配置的 token（请求头 Authorization: Bearer）；未配置 token 时留空', max_length=500, verbose_name='QQBot Token')),
                ('qqbot_timeout', models.PositiveSmallIntegerField(default=15, help_text='调用 NapCat HTTP 接口的超时时间，最小 1 秒', verbose_name='QQBot 超时(秒)')),
            ],
            options={
                'verbose_name': '消息推送设置',
                'verbose_name_plural': '消息推送设置',
                'db_table': 'push_setting',
            },
        ),
    ]
