# Generated by Django 6.0.6 on 2026-10-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0083_pushsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsetting',
            name='deploy_logs',
            field=models.TextField(blank=True, default='', help_text='最近一次一键部署的日志（JSON 文本），供后台页实时/回看展示', verbose_name='部署日志'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='deploy_state',
            field=models.CharField(blank=True, default='idle', help_text='idle 空闲 / running 进行中 / success 成功 / failed 失败（一键部署流水线的状态）', max_length=16, verbose_name='部署状态'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='deploy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='部署时间'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='napcat_dir',
            field=models.CharField(blank=True, default='', help_text='NapCat 的安装位置；留空则用项目下的 napcat/ 目录', max_length=300, verbose_name='NapCat 安装目录'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='napcat_qq',
            field=models.CharField(blank=True, default='', help_text='NapCat 要登录的 QQ 号（OneBot 的 self_id）；一键启动时用它快速登录（首次仍需扫码）', max_length=20, verbose_name='机器人 QQ 号'),
        ),
    ]
