# Generated by Django 6.0.6 on 2026-10-05 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0084_pushsetting_deploy_logs_pushsetting_deploy_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsetting',
            name='hook_base',
            field=models.CharField(blank=True, default='', help_text='NapCat 把事件 POST 回来的站点基址，如 https://api.example.com；留空则点「一键启动」时自动取当前访问本页的域名', max_length=200, verbose_name='事件回调基址'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='hook_secret',
            field=models.CharField(blank=True, default='', help_text='回调地址 /hook/qqbot/<密钥>/ 里的一段随机串，防伪造；新建时自动生成', max_length=64, verbose_name='事件回调密钥'),
        ),
        migrations.CreateModel(
            name='QQFriendRequest',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('user_id', models.CharField(db_index=True, max_length=20, verbose_name='申请人 QQ 号')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='申请人昵称')),
                ('reason', models.CharField(blank=True, default='', help_text='上游 request 事件里的 comment（验证消息 / 问候语）', max_length=255, verbose_name='申请理由')),
                ('flag', models.CharField(blank=True, default='', help_text='OneBot 的 flag，同意 / 拒绝时回传上游（事件上报时取得）', max_length=255, verbose_name='处理凭证')),
                ('sex', models.CharField(blank=True, default='', max_length=16, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已同意'), ('rejected', '已拒绝'), ('invalid', '已失效')], db_index=True, default='pending', help_text='待处理 / 已同意 / 已拒绝 / 已失效（申请被上游撤回等）', max_length=16, verbose_name='状态')),
                ('requested_at', models.DateTimeField(blank=True, help_text='事件里的时间戳（缺失则以入库时间为准）', null=True, verbose_name='申请时间')),
                ('handled_by', models.CharField(blank=True, default='', help_text='处理该申请的人：控制台=超管用户名；接口调用=发起项目 APPID；未认证为空', max_length=64, verbose_name='处理人')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_result', models.CharField(blank=True, default='', help_text='处理时的结果说明（成功或失败原因）', max_length=255, verbose_name='处理结果')),
            ],
            options={
                'verbose_name': 'QQ好友申请',
                'verbose_name_plural': 'QQ好友申请',
                'db_table': 'qq_friend_request',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['status', '-create_time'], name='qq_friend_req_status_idx')],
            },
        ),
    ]
