# Generated by Django 6.0.6 on 2026-10-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0085_qq_friend_request_hook'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qqfriendrequest',
            name='qq_friend_req_status_idx',
        ),
        migrations.DeleteModel(
            name='QQFriendRequest',
        ),
        migrations.RemoveField(
            model_name='pushsetting',
            name='hook_base',
        ),
        migrations.RemoveField(
            model_name='pushsetting',
            name='hook_secret',
        ),
    ]
