# Generated by Django 6.0.6 on 2026-10-06 01:14

import secrets

from django.db import migrations, models


def _default_hook_secret():
    """回调密钥默认值。

    原实现为 `API.models.Push.setting.default_hook_secret`；`PushSetting` 已随 QQBot 服务移出，
    本迁移只需保持可导入，故内联等价逻辑（随机 hex 串）。
    """
    return secrets.token_hex(16)


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0086_drop_qq_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsetting',
            name='hook_base',
            field=models.CharField(blank=True, default='', help_text='NapCat 把事件 POST 回来的站点基址，如 https://api.example.com；留空则点「一键启动」时自动取当前访问本页的域名', max_length=200, verbose_name='事件回调基址'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='hook_secret',
            field=models.CharField(blank=True, default=_default_hook_secret, help_text='回调地址 /hook/qqbot/<密钥>/ 里的一段随机串，防伪造；新建时自动生成', max_length=64, verbose_name='事件回调密钥'),
        ),
        migrations.CreateModel(
            name='QQPrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', help_text='OneBot 的 message_id，用于幂等（上游重推同一条时不再入库）', max_length=64, verbose_name='上游消息ID')),
                ('user_id', models.CharField(db_index=True, max_length=20, verbose_name='发送者 QQ 号')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='发送者昵称')),
                ('content', models.TextField(blank=True, default='', help_text='消息段拍平后的可读文本（非文本段以 [图片]/[语音] 等占位）', verbose_name='消息内容')),
                ('sub_type', models.CharField(blank=True, default='', help_text='OneBot 的 sub_type，如 friend / group / other', max_length=16, verbose_name='会话类型')),
                ('received_at', models.DateTimeField(blank=True, help_text='事件里的时间戳；缺失则以入库时间为准', null=True, verbose_name='消息时间')),
            ],
            options={
                'verbose_name': 'QQ私聊消息',
                'verbose_name_plural': 'QQ私聊消息',
                'db_table': 'qq_private_message',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['-id'], name='qq_priv_msg_id_idx')],
            },
        ),
    ]
