# Generated by Django 6.0.6 on 2026-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0087_qq_private_message_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqprivatemessage',
            name='direction',
            field=models.CharField(choices=[('in', '收到'), ('out', '发出')], db_index=True, default='in', help_text='in=好友发来；out=管理员在后台回复发出', max_length=8, verbose_name='方向'),
        ),
        migrations.AddField(
            model_name='qqprivatemessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='仅「收到」有意义：打开该会话即置为已读（用于未读角标）', verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='qqprivatemessage',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='好友昵称'),
        ),
        migrations.AlterField(
            model_name='qqprivatemessage',
            name='user_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='好友 QQ 号'),
        ),
        migrations.AddIndex(
            model_name='qqprivatemessage',
            index=models.Index(fields=['user_id', 'id'], name='qq_priv_msg_user_idx'),
        ),
    ]
