# Generated by Django 6.0.6 on 2026-10-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0088_qq_message_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqprivatemessage',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, help_text='手动标记，便于事后回看（不随已读变化）', verbose_name='星标'),
        ),
        migrations.AlterField(
            model_name='qqprivatemessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='仅「收到」有意义：打开该会话即置为已读（用于未读红点）', verbose_name='已读'),
        ),
    ]
