# Generated by Django 6.0.6 on 2026-10-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0089_qq_message_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsetting',
            name='ai_persona',
            field=models.CharField(choices=[('sarcastic', '尖酸刻薄'), ('gentle', '温柔善良聪明可爱'), ('humorous', '幽默搞笑')], default='gentle', help_text='自动回复使用的人格风格（三种内置人设，提示词在代码里维护）', max_length=16, verbose_name='AI 人格'),
        ),
        migrations.AddField(
            model_name='pushsetting',
            name='ai_reply_enabled',
            field=models.BooleanField(default=False, help_text='打开后，好友私聊消息会交给 AI 判断并自动回复；关闭则完全不影响现有功能', verbose_name='AI 自动回复'),
        ),
    ]
