# Generated by Django 6.0.6 on 2026-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0090_pushsetting_ai_persona_pushsetting_ai_reply_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigration',
            name='dlwz_first_image',
            field=models.CharField(blank=True, default='', help_text='丸子上手上传的首图地址（为空表示尚未上传），供转传到代练通首图使用', max_length=500, verbose_name='丸子打手首图URL'),
        ),
    ]
