# Generated by Django 6.0.6 on 2026-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0093_alter_ordermigration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqprivatemessage',
            name='is_greeting',
            field=models.BooleanField(default=False, help_text='代练搬单给「刚加我们好友的打手」发的主动开场白（direction=out）；据此把该 QQ 认作来交接的打手，后续私聊按客服口径引导', verbose_name='业务开场白'),
        ),
    ]
