# Generated by Django 6.0.6 on 2026-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0094_qqprivatemessage_is_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigration',
            name='dlt_first_image',
            field=models.CharField(blank=True, default='', help_text='已成功转传到代练通的首图（转传成功后回填，用来避免每轮重复上传）', max_length=500, verbose_name='已转传代练通的首图URL'),
        ),
    ]
