# Generated by Django 6.0.6 on 2026-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0096_alter_ordermigration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigration',
            name='owner_info_sent',
            field=models.BooleanField(default=False, help_text='已把号主信息发给打手；一旦为 True 就绝不再重复发送（不管是谁来问）', verbose_name='号主信息已发送'),
        ),
    ]
