# Generated by Django 6.0.6 on 2026-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0097_ordermigration_owner_info_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigration',
            name='booster_cancel_asked',
            field=models.BooleanField(default=False, help_text='打手提过退单、我们已劝阻一次；他再次确认要退单才落库并通知管理员', verbose_name='退单已劝阻'),
        ),
        migrations.AddField(
            model_name='ordermigration',
            name='booster_cancel_notified',
            field=models.BooleanField(default=False, help_text='已就「打手申请退单」通知过管理员（Server酱 + QQBot）；为 True 则不重复通知', verbose_name='退单已通知'),
        ),
        migrations.AddField(
            model_name='ordermigration',
            name='booster_qq',
            field=models.CharField(blank=True, default='', help_text='在 QQ 上向我们报过单号的打手 QQ，退单通知时带给我们便于联系', max_length=32, verbose_name='打手QQ'),
        ),
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='notify_qq',
            field=models.CharField(blank=True, default='3091995257', help_text='打手申请退单等需要人工处理的事件，用 QQBot 私聊通知这个 QQ', max_length=32, verbose_name='管理员QQ'),
        ),
        migrations.AlterField(
            model_name='ordermigration',
            name='status',
            field=models.CharField(choices=[('candidate', '已抓取（未发布）'), ('publishing', '发单中（未确认）'), ('published', '已发丸子（待接单）'), ('taker_joined', '丸子已接单（待报单号）'), ('taken', '代练通已接单'), ('waiting_accept', '等待验收中'), ('settled', '已结算'), ('booster_cancel', '打手申请退单'), ('failed', '失败'), ('cancelled', '已撤单')], db_index=True, default='candidate', max_length=16, verbose_name='状态'),
        ),
    ]
