# Generated by Django 6.0.6 on 2026-10-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0098_ordermigration_booster_cancel_asked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermigrationsetting',
            name='run_lock_until',
            field=models.DateTimeField(blank=True, help_text='跨进程互斥：某进程正在执行一轮时写为「now + 占用时长」，结束时清空。生产是多 worker（uwsgi lazy-apps），每个 worker 各有一份搬单线程且同步唤醒，不加锁会把同一笔订单重复发到丸子；进程被 kill 时该值到期自动失效，不会把锁永久占死（见 order_migration.utils 的 RUN_LOCK_TTL_SECONDS）', null=True, verbose_name='本轮执行占用到期'),
        ),
    ]
