# Generated by Django 6.1.2 on 2026-10-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0099_ordermigrationsetting_run_lock_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMigration',
        ),
        migrations.DeleteModel(
            name='OrderMigrationBlacklist',
        ),
        migrations.DeleteModel(
            name='OrderMigrationSetting',
        ),
        migrations.RemoveField(
            model_name='qqprivatemessage',
            name='is_greeting',
        ),
    ]
