# Generated by Django 6.1.2 on 2026-10-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0100_delete_ordermigration_delete_ordermigrationblacklist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSetting',
        ),
        migrations.RemoveIndex(
            model_name='qqprivatemessage',
            name='qq_priv_msg_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='qqprivatemessage',
            name='qq_priv_msg_user_idx',
        ),
        migrations.DeleteModel(
            name='QQPrivateMessage',
        ),
    ]
