# Generated by Django 6.1.2 on 2026-10-09 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0101_delete_pushsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('app_id', models.CharField(blank=True, db_index=True, help_text='创建该任务的接入项目 APPID；任务按此隔离，调用方只能操作自己的任务', max_length=64, verbose_name='归属项目')),
                ('recipients', models.CharField(help_text='收件人邮箱，多个用逗号分隔', max_length=1000, verbose_name='收件人')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件标题')),
                ('body', models.TextField(verbose_name='邮件正文')),
                ('interval_minutes', models.PositiveIntegerField(default=0, help_text='0=只发送一次；大于 0=每隔该分钟数重复发送，直到手动停用或删除', verbose_name='发送间隔(分钟)')),
                ('enabled', models.BooleanField(default=True, help_text='停用后不再调度（任务与历史记录保留）', verbose_name='启用')),
                ('next_run_at', models.DateTimeField(blank=True, help_text='调度游标：到期即发送；为空表示不再调度（一次性任务发送后置空）', null=True, verbose_name='下次发送时间')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='上次发送时间')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='累计发送次数')),
                ('last_ok', models.BooleanField(blank=True, help_text='从未发送时为空；发送失败只记录、不自动重试', null=True, verbose_name='上次是否成功')),
                ('last_message', models.CharField(blank=True, default='', max_length=500, verbose_name='上次结果说明')),
            ],
            options={
                'verbose_name': '邮件定时任务',
                'verbose_name_plural': '邮件定时任务',
                'db_table': 'push_email_task',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['enabled', 'next_run_at'], name='push_email_task_due_idx')],
            },
        ),
    ]
